// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type GrantsGranteeInitParameters struct {
}

type GrantsGranteeObservation struct {
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	EmailAddress *string `json:"emailAddress,omitempty" tf:"email_address,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`
}

type GrantsGranteeParameters struct {
}

type ObjectstorageObjectACLGrantsInitParameters struct {
}

type ObjectstorageObjectACLGrantsObservation struct {
	Grantee *GrantsGranteeObservation `json:"grantee,omitempty" tf:"grantee,omitempty"`

	Permission *string `json:"permission,omitempty" tf:"permission,omitempty"`
}

type ObjectstorageObjectACLGrantsParameters struct {
}

type ObjectstorageObjectACLInitParameters struct {

	// Target object id
	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/objectstorage/v1alpha1.ObjectstorageObject
	ObjectID *string `json:"objectId,omitempty" tf:"object_id,omitempty"`

	// Reference to a ObjectstorageObject in objectstorage to populate objectId.
	// +kubebuilder:validation:Optional
	ObjectIDRef *v1.NamespacedReference `json:"objectIdRef,omitempty" tf:"-"`

	// Selector for a ObjectstorageObject in objectstorage to populate objectId.
	// +kubebuilder:validation:Optional
	ObjectIDSelector *v1.NamespacedSelector `json:"objectIdSelector,omitempty" tf:"-"`

	Rule *string `json:"rule,omitempty" tf:"rule,omitempty"`
}

type ObjectstorageObjectACLObservation struct {
	Grants []ObjectstorageObjectACLGrantsObservation `json:"grants,omitempty" tf:"grants,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Target object id
	ObjectID *string `json:"objectId,omitempty" tf:"object_id,omitempty"`

	OwnerDisplayname *string `json:"ownerDisplayname,omitempty" tf:"owner_displayname,omitempty"`

	OwnerID *string `json:"ownerId,omitempty" tf:"owner_id,omitempty"`

	Rule *string `json:"rule,omitempty" tf:"rule,omitempty"`
}

type ObjectstorageObjectACLParameters struct {

	// Target object id
	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/objectstorage/v1alpha1.ObjectstorageObject
	// +kubebuilder:validation:Optional
	ObjectID *string `json:"objectId,omitempty" tf:"object_id,omitempty"`

	// Reference to a ObjectstorageObject in objectstorage to populate objectId.
	// +kubebuilder:validation:Optional
	ObjectIDRef *v1.NamespacedReference `json:"objectIdRef,omitempty" tf:"-"`

	// Selector for a ObjectstorageObject in objectstorage to populate objectId.
	// +kubebuilder:validation:Optional
	ObjectIDSelector *v1.NamespacedSelector `json:"objectIdSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	Rule *string `json:"rule,omitempty" tf:"rule,omitempty"`
}

// ObjectstorageObjectACLSpec defines the desired state of ObjectstorageObjectACL
type ObjectstorageObjectACLSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ObjectstorageObjectACLParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ObjectstorageObjectACLInitParameters `json:"initProvider,omitempty"`
}

// ObjectstorageObjectACLStatus defines the observed state of ObjectstorageObjectACL.
type ObjectstorageObjectACLStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ObjectstorageObjectACLObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ObjectstorageObjectACL is the Schema for the ObjectstorageObjectACLs API. NAVER Cloud Platform objectstorage object acl resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,ncloud}
type ObjectstorageObjectACL struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.rule) || (has(self.initProvider) && has(self.initProvider.rule))",message="spec.forProvider.rule is a required parameter"
	Spec   ObjectstorageObjectACLSpec   `json:"spec"`
	Status ObjectstorageObjectACLStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ObjectstorageObjectACLList contains a list of ObjectstorageObjectACLs
type ObjectstorageObjectACLList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ObjectstorageObjectACL `json:"items"`
}

// Repository type metadata.
var (
	ObjectstorageObjectACL_Kind             = "ObjectstorageObjectACL"
	ObjectstorageObjectACL_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ObjectstorageObjectACL_Kind}.String()
	ObjectstorageObjectACL_KindAPIVersion   = ObjectstorageObjectACL_Kind + "." + CRDGroupVersion.String()
	ObjectstorageObjectACL_GroupVersionKind = CRDGroupVersion.WithKind(ObjectstorageObjectACL_Kind)
)

func init() {
	SchemeBuilder.Register(&ObjectstorageObjectACL{}, &ObjectstorageObjectACLList{})
}
