// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ObjectstorageBucketInitParameters struct {

	// Bucket Name for Object Storage
	BucketName *string `json:"bucketName,omitempty" tf:"bucket_name,omitempty"`
}

type ObjectstorageBucketObservation struct {

	// Bucket Name for Object Storage
	BucketName *string `json:"bucketName,omitempty" tf:"bucket_name,omitempty"`

	CreationDate *string `json:"creationDate,omitempty" tf:"creation_date,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type ObjectstorageBucketParameters struct {

	// Bucket Name for Object Storage
	// +kubebuilder:validation:Optional
	BucketName *string `json:"bucketName,omitempty" tf:"bucket_name,omitempty"`
}

// ObjectstorageBucketSpec defines the desired state of ObjectstorageBucket
type ObjectstorageBucketSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ObjectstorageBucketParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ObjectstorageBucketInitParameters `json:"initProvider,omitempty"`
}

// ObjectstorageBucketStatus defines the observed state of ObjectstorageBucket.
type ObjectstorageBucketStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ObjectstorageBucketObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ObjectstorageBucket is the Schema for the ObjectstorageBuckets API. NAVER Cloud Platform objectstorage bucket resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,ncloud}
type ObjectstorageBucket struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.bucketName) || (has(self.initProvider) && has(self.initProvider.bucketName))",message="spec.forProvider.bucketName is a required parameter"
	Spec   ObjectstorageBucketSpec   `json:"spec"`
	Status ObjectstorageBucketStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ObjectstorageBucketList contains a list of ObjectstorageBuckets
type ObjectstorageBucketList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ObjectstorageBucket `json:"items"`
}

// Repository type metadata.
var (
	ObjectstorageBucket_Kind             = "ObjectstorageBucket"
	ObjectstorageBucket_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ObjectstorageBucket_Kind}.String()
	ObjectstorageBucket_KindAPIVersion   = ObjectstorageBucket_Kind + "." + CRDGroupVersion.String()
	ObjectstorageBucket_GroupVersionKind = CRDGroupVersion.WithKind(ObjectstorageBucket_Kind)
)

func init() {
	SchemeBuilder.Register(&ObjectstorageBucket{}, &ObjectstorageBucketList{})
}
