// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type GranteeInitParameters struct {
}

type GranteeObservation struct {
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	EmailAddress *string `json:"emailAddress,omitempty" tf:"email_address,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`
}

type GranteeParameters struct {
}

type GrantsInitParameters struct {
}

type GrantsObservation struct {
	Grantee *GranteeObservation `json:"grantee,omitempty" tf:"grantee,omitempty"`

	Permission *string `json:"permission,omitempty" tf:"permission,omitempty"`
}

type GrantsParameters struct {
}

type ObjectstorageBucketACLInitParameters struct {

	// Target bucket name
	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/objectstorage/v1alpha1.ObjectstorageBucket
	BucketName *string `json:"bucketName,omitempty" tf:"bucket_name,omitempty"`

	// Reference to a ObjectstorageBucket in objectstorage to populate bucketName.
	// +kubebuilder:validation:Optional
	BucketNameRef *v1.NamespacedReference `json:"bucketNameRef,omitempty" tf:"-"`

	// Selector for a ObjectstorageBucket in objectstorage to populate bucketName.
	// +kubebuilder:validation:Optional
	BucketNameSelector *v1.NamespacedSelector `json:"bucketNameSelector,omitempty" tf:"-"`

	Rule *string `json:"rule,omitempty" tf:"rule,omitempty"`
}

type ObjectstorageBucketACLObservation struct {

	// Target bucket name
	BucketName *string `json:"bucketName,omitempty" tf:"bucket_name,omitempty"`

	Grants []GrantsObservation `json:"grants,omitempty" tf:"grants,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	Rule *string `json:"rule,omitempty" tf:"rule,omitempty"`
}

type ObjectstorageBucketACLParameters struct {

	// Target bucket name
	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/objectstorage/v1alpha1.ObjectstorageBucket
	// +kubebuilder:validation:Optional
	BucketName *string `json:"bucketName,omitempty" tf:"bucket_name,omitempty"`

	// Reference to a ObjectstorageBucket in objectstorage to populate bucketName.
	// +kubebuilder:validation:Optional
	BucketNameRef *v1.NamespacedReference `json:"bucketNameRef,omitempty" tf:"-"`

	// Selector for a ObjectstorageBucket in objectstorage to populate bucketName.
	// +kubebuilder:validation:Optional
	BucketNameSelector *v1.NamespacedSelector `json:"bucketNameSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	Rule *string `json:"rule,omitempty" tf:"rule,omitempty"`
}

// ObjectstorageBucketACLSpec defines the desired state of ObjectstorageBucketACL
type ObjectstorageBucketACLSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ObjectstorageBucketACLParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ObjectstorageBucketACLInitParameters `json:"initProvider,omitempty"`
}

// ObjectstorageBucketACLStatus defines the observed state of ObjectstorageBucketACL.
type ObjectstorageBucketACLStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ObjectstorageBucketACLObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ObjectstorageBucketACL is the Schema for the ObjectstorageBucketACLs API. NAVER Cloud Platform objectstorage bucket acl resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,ncloud}
type ObjectstorageBucketACL struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.rule) || (has(self.initProvider) && has(self.initProvider.rule))",message="spec.forProvider.rule is a required parameter"
	Spec   ObjectstorageBucketACLSpec   `json:"spec"`
	Status ObjectstorageBucketACLStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ObjectstorageBucketACLList contains a list of ObjectstorageBucketACLs
type ObjectstorageBucketACLList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ObjectstorageBucketACL `json:"items"`
}

// Repository type metadata.
var (
	ObjectstorageBucketACL_Kind             = "ObjectstorageBucketACL"
	ObjectstorageBucketACL_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ObjectstorageBucketACL_Kind}.String()
	ObjectstorageBucketACL_KindAPIVersion   = ObjectstorageBucketACL_Kind + "." + CRDGroupVersion.String()
	ObjectstorageBucketACL_GroupVersionKind = CRDGroupVersion.WithKind(ObjectstorageBucketACL_Kind)
)

func init() {
	SchemeBuilder.Register(&ObjectstorageBucketACL{}, &ObjectstorageBucketACLList{})
}
