//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessEntriesInitParameters) DeepCopyInto(out *AccessEntriesInitParameters) {
	*out = *in
	if in.Entry != nil {
		in, out := &in.Entry, &out.Entry
		*out = new(string)
		**out = **in
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]PoliciesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessEntriesInitParameters.
func (in *AccessEntriesInitParameters) DeepCopy() *AccessEntriesInitParameters {
	if in == nil {
		return nil
	}
	out := new(AccessEntriesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessEntriesObservation) DeepCopyInto(out *AccessEntriesObservation) {
	*out = *in
	if in.Entry != nil {
		in, out := &in.Entry, &out.Entry
		*out = new(string)
		**out = **in
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]PoliciesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessEntriesObservation.
func (in *AccessEntriesObservation) DeepCopy() *AccessEntriesObservation {
	if in == nil {
		return nil
	}
	out := new(AccessEntriesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessEntriesParameters) DeepCopyInto(out *AccessEntriesParameters) {
	*out = *in
	if in.Entry != nil {
		in, out := &in.Entry, &out.Entry
		*out = new(string)
		**out = **in
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]PoliciesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessEntriesParameters.
func (in *AccessEntriesParameters) DeepCopy() *AccessEntriesParameters {
	if in == nil {
		return nil
	}
	out := new(AccessEntriesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscaleInitParameters) DeepCopyInto(out *AutoscaleInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(float64)
		**out = **in
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscaleInitParameters.
func (in *AutoscaleInitParameters) DeepCopy() *AutoscaleInitParameters {
	if in == nil {
		return nil
	}
	out := new(AutoscaleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscaleObservation) DeepCopyInto(out *AutoscaleObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(float64)
		**out = **in
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscaleObservation.
func (in *AutoscaleObservation) DeepCopy() *AutoscaleObservation {
	if in == nil {
		return nil
	}
	out := new(AutoscaleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscaleParameters) DeepCopyInto(out *AutoscaleParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(float64)
		**out = **in
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscaleParameters.
func (in *AutoscaleParameters) DeepCopy() *AutoscaleParameters {
	if in == nil {
		return nil
	}
	out := new(AutoscaleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricClusterInitParameters) DeepCopyInto(out *FabricClusterInitParameters) {
	*out = *in
	if in.PoolName != nil {
		in, out := &in.PoolName, &out.PoolName
		*out = new(string)
		**out = **in
	}
	if in.PoolNo != nil {
		in, out := &in.PoolNo, &out.PoolNo
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricClusterInitParameters.
func (in *FabricClusterInitParameters) DeepCopy() *FabricClusterInitParameters {
	if in == nil {
		return nil
	}
	out := new(FabricClusterInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricClusterObservation) DeepCopyInto(out *FabricClusterObservation) {
	*out = *in
	if in.PoolName != nil {
		in, out := &in.PoolName, &out.PoolName
		*out = new(string)
		**out = **in
	}
	if in.PoolNo != nil {
		in, out := &in.PoolNo, &out.PoolNo
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricClusterObservation.
func (in *FabricClusterObservation) DeepCopy() *FabricClusterObservation {
	if in == nil {
		return nil
	}
	out := new(FabricClusterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricClusterParameters) DeepCopyInto(out *FabricClusterParameters) {
	*out = *in
	if in.PoolName != nil {
		in, out := &in.PoolName, &out.PoolName
		*out = new(string)
		**out = **in
	}
	if in.PoolNo != nil {
		in, out := &in.PoolNo, &out.PoolNo
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricClusterParameters.
func (in *FabricClusterParameters) DeepCopy() *FabricClusterParameters {
	if in == nil {
		return nil
	}
	out := new(FabricClusterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPACLInitParameters) DeepCopyInto(out *IPACLInitParameters) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPACLInitParameters.
func (in *IPACLInitParameters) DeepCopy() *IPACLInitParameters {
	if in == nil {
		return nil
	}
	out := new(IPACLInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPACLObservation) DeepCopyInto(out *IPACLObservation) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPACLObservation.
func (in *IPACLObservation) DeepCopy() *IPACLObservation {
	if in == nil {
		return nil
	}
	out := new(IPACLObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPACLParameters) DeepCopyInto(out *IPACLParameters) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPACLParameters.
func (in *IPACLParameters) DeepCopy() *IPACLParameters {
	if in == nil {
		return nil
	}
	out := new(IPACLParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelInitParameters) DeepCopyInto(out *LabelInitParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelInitParameters.
func (in *LabelInitParameters) DeepCopy() *LabelInitParameters {
	if in == nil {
		return nil
	}
	out := new(LabelInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelObservation) DeepCopyInto(out *LabelObservation) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelObservation.
func (in *LabelObservation) DeepCopy() *LabelObservation {
	if in == nil {
		return nil
	}
	out := new(LabelObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelParameters) DeepCopyInto(out *LabelParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelParameters.
func (in *LabelParameters) DeepCopy() *LabelParameters {
	if in == nil {
		return nil
	}
	out := new(LabelParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogInitParameters) DeepCopyInto(out *LogInitParameters) {
	*out = *in
	if in.Audit != nil {
		in, out := &in.Audit, &out.Audit
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogInitParameters.
func (in *LogInitParameters) DeepCopy() *LogInitParameters {
	if in == nil {
		return nil
	}
	out := new(LogInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogObservation) DeepCopyInto(out *LogObservation) {
	*out = *in
	if in.Audit != nil {
		in, out := &in.Audit, &out.Audit
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogObservation.
func (in *LogObservation) DeepCopy() *LogObservation {
	if in == nil {
		return nil
	}
	out := new(LogObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogParameters) DeepCopyInto(out *LogParameters) {
	*out = *in
	if in.Audit != nil {
		in, out := &in.Audit, &out.Audit
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogParameters.
func (in *LogParameters) DeepCopy() *LogParameters {
	if in == nil {
		return nil
	}
	out := new(LogParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NksCluster) DeepCopyInto(out *NksCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NksCluster.
func (in *NksCluster) DeepCopy() *NksCluster {
	if in == nil {
		return nil
	}
	out := new(NksCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NksCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NksClusterInitParameters) DeepCopyInto(out *NksClusterInitParameters) {
	*out = *in
	if in.AccessEntries != nil {
		in, out := &in.AccessEntries, &out.AccessEntries
		*out = make([]AccessEntriesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AuthType != nil {
		in, out := &in.AuthType, &out.AuthType
		*out = new(string)
		**out = **in
	}
	if in.ClusterType != nil {
		in, out := &in.ClusterType, &out.ClusterType
		*out = new(string)
		**out = **in
	}
	if in.HypervisorCode != nil {
		in, out := &in.HypervisorCode, &out.HypervisorCode
		*out = new(string)
		**out = **in
	}
	if in.IPACL != nil {
		in, out := &in.IPACL, &out.IPACL
		*out = make([]IPACLInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IPACLDefaultAction != nil {
		in, out := &in.IPACLDefaultAction, &out.IPACLDefaultAction
		*out = new(string)
		**out = **in
	}
	if in.K8SVersion != nil {
		in, out := &in.K8SVersion, &out.K8SVersion
		*out = new(string)
		**out = **in
	}
	if in.KMSKeyTag != nil {
		in, out := &in.KMSKeyTag, &out.KMSKeyTag
		*out = new(string)
		**out = **in
	}
	if in.KubeNetworkPlugin != nil {
		in, out := &in.KubeNetworkPlugin, &out.KubeNetworkPlugin
		*out = new(string)
		**out = **in
	}
	if in.LBPrivateSubnetNo != nil {
		in, out := &in.LBPrivateSubnetNo, &out.LBPrivateSubnetNo
		*out = new(string)
		**out = **in
	}
	if in.LBPrivateSubnetNoRef != nil {
		in, out := &in.LBPrivateSubnetNoRef, &out.LBPrivateSubnetNoRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.LBPrivateSubnetNoSelector != nil {
		in, out := &in.LBPrivateSubnetNoSelector, &out.LBPrivateSubnetNoSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.LBPublicSubnetNo != nil {
		in, out := &in.LBPublicSubnetNo, &out.LBPublicSubnetNo
		*out = new(string)
		**out = **in
	}
	if in.LBPublicSubnetNoRef != nil {
		in, out := &in.LBPublicSubnetNoRef, &out.LBPublicSubnetNoRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.LBPublicSubnetNoSelector != nil {
		in, out := &in.LBPublicSubnetNoSelector, &out.LBPublicSubnetNoSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Log != nil {
		in, out := &in.Log, &out.Log
		*out = make([]LogInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LoginKeyName != nil {
		in, out := &in.LoginKeyName, &out.LoginKeyName
		*out = new(string)
		**out = **in
	}
	if in.LoginKeyNameRef != nil {
		in, out := &in.LoginKeyNameRef, &out.LoginKeyNameRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.LoginKeyNameSelector != nil {
		in, out := &in.LoginKeyNameSelector, &out.LoginKeyNameSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Oidc != nil {
		in, out := &in.Oidc, &out.Oidc
		*out = make([]OidcInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PublicNetwork != nil {
		in, out := &in.PublicNetwork, &out.PublicNetwork
		*out = new(bool)
		**out = **in
	}
	if in.ReturnProtection != nil {
		in, out := &in.ReturnProtection, &out.ReturnProtection
		*out = new(bool)
		**out = **in
	}
	if in.SubnetNoList != nil {
		in, out := &in.SubnetNoList, &out.SubnetNoList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SubnetNoRefs != nil {
		in, out := &in.SubnetNoRefs, &out.SubnetNoRefs
		*out = make([]v1.NamespacedReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SubnetNoSelector != nil {
		in, out := &in.SubnetNoSelector, &out.SubnetNoSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.VPCNo != nil {
		in, out := &in.VPCNo, &out.VPCNo
		*out = new(string)
		**out = **in
	}
	if in.VPCNoRef != nil {
		in, out := &in.VPCNoRef, &out.VPCNoRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.VPCNoSelector != nil {
		in, out := &in.VPCNoSelector, &out.VPCNoSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Zone != nil {
		in, out := &in.Zone, &out.Zone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NksClusterInitParameters.
func (in *NksClusterInitParameters) DeepCopy() *NksClusterInitParameters {
	if in == nil {
		return nil
	}
	out := new(NksClusterInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NksClusterList) DeepCopyInto(out *NksClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NksCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NksClusterList.
func (in *NksClusterList) DeepCopy() *NksClusterList {
	if in == nil {
		return nil
	}
	out := new(NksClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NksClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NksClusterObservation) DeepCopyInto(out *NksClusterObservation) {
	*out = *in
	if in.AccessEntries != nil {
		in, out := &in.AccessEntries, &out.AccessEntries
		*out = make([]AccessEntriesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AcgNo != nil {
		in, out := &in.AcgNo, &out.AcgNo
		*out = new(string)
		**out = **in
	}
	if in.AuthType != nil {
		in, out := &in.AuthType, &out.AuthType
		*out = new(string)
		**out = **in
	}
	if in.ClusterType != nil {
		in, out := &in.ClusterType, &out.ClusterType
		*out = new(string)
		**out = **in
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.HypervisorCode != nil {
		in, out := &in.HypervisorCode, &out.HypervisorCode
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IPACL != nil {
		in, out := &in.IPACL, &out.IPACL
		*out = make([]IPACLObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IPACLDefaultAction != nil {
		in, out := &in.IPACLDefaultAction, &out.IPACLDefaultAction
		*out = new(string)
		**out = **in
	}
	if in.K8SVersion != nil {
		in, out := &in.K8SVersion, &out.K8SVersion
		*out = new(string)
		**out = **in
	}
	if in.KMSKeyTag != nil {
		in, out := &in.KMSKeyTag, &out.KMSKeyTag
		*out = new(string)
		**out = **in
	}
	if in.KubeNetworkPlugin != nil {
		in, out := &in.KubeNetworkPlugin, &out.KubeNetworkPlugin
		*out = new(string)
		**out = **in
	}
	if in.LBPrivateSubnetNo != nil {
		in, out := &in.LBPrivateSubnetNo, &out.LBPrivateSubnetNo
		*out = new(string)
		**out = **in
	}
	if in.LBPublicSubnetNo != nil {
		in, out := &in.LBPublicSubnetNo, &out.LBPublicSubnetNo
		*out = new(string)
		**out = **in
	}
	if in.Log != nil {
		in, out := &in.Log, &out.Log
		*out = make([]LogObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LoginKeyName != nil {
		in, out := &in.LoginKeyName, &out.LoginKeyName
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Oidc != nil {
		in, out := &in.Oidc, &out.Oidc
		*out = make([]OidcObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PublicNetwork != nil {
		in, out := &in.PublicNetwork, &out.PublicNetwork
		*out = new(bool)
		**out = **in
	}
	if in.ReturnProtection != nil {
		in, out := &in.ReturnProtection, &out.ReturnProtection
		*out = new(bool)
		**out = **in
	}
	if in.SubnetNoList != nil {
		in, out := &in.SubnetNoList, &out.SubnetNoList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.VPCNo != nil {
		in, out := &in.VPCNo, &out.VPCNo
		*out = new(string)
		**out = **in
	}
	if in.Zone != nil {
		in, out := &in.Zone, &out.Zone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NksClusterObservation.
func (in *NksClusterObservation) DeepCopy() *NksClusterObservation {
	if in == nil {
		return nil
	}
	out := new(NksClusterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NksClusterParameters) DeepCopyInto(out *NksClusterParameters) {
	*out = *in
	if in.AccessEntries != nil {
		in, out := &in.AccessEntries, &out.AccessEntries
		*out = make([]AccessEntriesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AuthType != nil {
		in, out := &in.AuthType, &out.AuthType
		*out = new(string)
		**out = **in
	}
	if in.ClusterType != nil {
		in, out := &in.ClusterType, &out.ClusterType
		*out = new(string)
		**out = **in
	}
	if in.HypervisorCode != nil {
		in, out := &in.HypervisorCode, &out.HypervisorCode
		*out = new(string)
		**out = **in
	}
	if in.IPACL != nil {
		in, out := &in.IPACL, &out.IPACL
		*out = make([]IPACLParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IPACLDefaultAction != nil {
		in, out := &in.IPACLDefaultAction, &out.IPACLDefaultAction
		*out = new(string)
		**out = **in
	}
	if in.K8SVersion != nil {
		in, out := &in.K8SVersion, &out.K8SVersion
		*out = new(string)
		**out = **in
	}
	if in.KMSKeyTag != nil {
		in, out := &in.KMSKeyTag, &out.KMSKeyTag
		*out = new(string)
		**out = **in
	}
	if in.KubeNetworkPlugin != nil {
		in, out := &in.KubeNetworkPlugin, &out.KubeNetworkPlugin
		*out = new(string)
		**out = **in
	}
	if in.LBPrivateSubnetNo != nil {
		in, out := &in.LBPrivateSubnetNo, &out.LBPrivateSubnetNo
		*out = new(string)
		**out = **in
	}
	if in.LBPrivateSubnetNoRef != nil {
		in, out := &in.LBPrivateSubnetNoRef, &out.LBPrivateSubnetNoRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.LBPrivateSubnetNoSelector != nil {
		in, out := &in.LBPrivateSubnetNoSelector, &out.LBPrivateSubnetNoSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.LBPublicSubnetNo != nil {
		in, out := &in.LBPublicSubnetNo, &out.LBPublicSubnetNo
		*out = new(string)
		**out = **in
	}
	if in.LBPublicSubnetNoRef != nil {
		in, out := &in.LBPublicSubnetNoRef, &out.LBPublicSubnetNoRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.LBPublicSubnetNoSelector != nil {
		in, out := &in.LBPublicSubnetNoSelector, &out.LBPublicSubnetNoSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Log != nil {
		in, out := &in.Log, &out.Log
		*out = make([]LogParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LoginKeyName != nil {
		in, out := &in.LoginKeyName, &out.LoginKeyName
		*out = new(string)
		**out = **in
	}
	if in.LoginKeyNameRef != nil {
		in, out := &in.LoginKeyNameRef, &out.LoginKeyNameRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.LoginKeyNameSelector != nil {
		in, out := &in.LoginKeyNameSelector, &out.LoginKeyNameSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Oidc != nil {
		in, out := &in.Oidc, &out.Oidc
		*out = make([]OidcParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PublicNetwork != nil {
		in, out := &in.PublicNetwork, &out.PublicNetwork
		*out = new(bool)
		**out = **in
	}
	if in.ReturnProtection != nil {
		in, out := &in.ReturnProtection, &out.ReturnProtection
		*out = new(bool)
		**out = **in
	}
	if in.SubnetNoList != nil {
		in, out := &in.SubnetNoList, &out.SubnetNoList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SubnetNoRefs != nil {
		in, out := &in.SubnetNoRefs, &out.SubnetNoRefs
		*out = make([]v1.NamespacedReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SubnetNoSelector != nil {
		in, out := &in.SubnetNoSelector, &out.SubnetNoSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.VPCNo != nil {
		in, out := &in.VPCNo, &out.VPCNo
		*out = new(string)
		**out = **in
	}
	if in.VPCNoRef != nil {
		in, out := &in.VPCNoRef, &out.VPCNoRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.VPCNoSelector != nil {
		in, out := &in.VPCNoSelector, &out.VPCNoSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Zone != nil {
		in, out := &in.Zone, &out.Zone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NksClusterParameters.
func (in *NksClusterParameters) DeepCopy() *NksClusterParameters {
	if in == nil {
		return nil
	}
	out := new(NksClusterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NksClusterSpec) DeepCopyInto(out *NksClusterSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NksClusterSpec.
func (in *NksClusterSpec) DeepCopy() *NksClusterSpec {
	if in == nil {
		return nil
	}
	out := new(NksClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NksClusterStatus) DeepCopyInto(out *NksClusterStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NksClusterStatus.
func (in *NksClusterStatus) DeepCopy() *NksClusterStatus {
	if in == nil {
		return nil
	}
	out := new(NksClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NksNodePool) DeepCopyInto(out *NksNodePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NksNodePool.
func (in *NksNodePool) DeepCopy() *NksNodePool {
	if in == nil {
		return nil
	}
	out := new(NksNodePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NksNodePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NksNodePoolInitParameters) DeepCopyInto(out *NksNodePoolInitParameters) {
	*out = *in
	if in.Autoscale != nil {
		in, out := &in.Autoscale, &out.Autoscale
		*out = make([]AutoscaleInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClusterUUID != nil {
		in, out := &in.ClusterUUID, &out.ClusterUUID
		*out = new(string)
		**out = **in
	}
	if in.ClusterUUIDRef != nil {
		in, out := &in.ClusterUUIDRef, &out.ClusterUUIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterUUIDSelector != nil {
		in, out := &in.ClusterUUIDSelector, &out.ClusterUUIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.FabricCluster != nil {
		in, out := &in.FabricCluster, &out.FabricCluster
		*out = make([]FabricClusterInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.K8SVersion != nil {
		in, out := &in.K8SVersion, &out.K8SVersion
		*out = new(string)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = make([]LabelInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeCount != nil {
		in, out := &in.NodeCount, &out.NodeCount
		*out = new(float64)
		**out = **in
	}
	if in.NodePoolName != nil {
		in, out := &in.NodePoolName, &out.NodePoolName
		*out = new(string)
		**out = **in
	}
	if in.ProductCode != nil {
		in, out := &in.ProductCode, &out.ProductCode
		*out = new(string)
		**out = **in
	}
	if in.ServerRoleID != nil {
		in, out := &in.ServerRoleID, &out.ServerRoleID
		*out = new(string)
		**out = **in
	}
	if in.ServerSpecCode != nil {
		in, out := &in.ServerSpecCode, &out.ServerSpecCode
		*out = new(string)
		**out = **in
	}
	if in.SoftwareCode != nil {
		in, out := &in.SoftwareCode, &out.SoftwareCode
		*out = new(string)
		**out = **in
	}
	if in.StorageSize != nil {
		in, out := &in.StorageSize, &out.StorageSize
		*out = new(float64)
		**out = **in
	}
	if in.SubnetNo != nil {
		in, out := &in.SubnetNo, &out.SubnetNo
		*out = new(string)
		**out = **in
	}
	if in.SubnetNoList != nil {
		in, out := &in.SubnetNoList, &out.SubnetNoList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Taint != nil {
		in, out := &in.Taint, &out.Taint
		*out = make([]TaintInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NksNodePoolInitParameters.
func (in *NksNodePoolInitParameters) DeepCopy() *NksNodePoolInitParameters {
	if in == nil {
		return nil
	}
	out := new(NksNodePoolInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NksNodePoolList) DeepCopyInto(out *NksNodePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NksNodePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NksNodePoolList.
func (in *NksNodePoolList) DeepCopy() *NksNodePoolList {
	if in == nil {
		return nil
	}
	out := new(NksNodePoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NksNodePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NksNodePoolObservation) DeepCopyInto(out *NksNodePoolObservation) {
	*out = *in
	if in.Autoscale != nil {
		in, out := &in.Autoscale, &out.Autoscale
		*out = make([]AutoscaleObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClusterUUID != nil {
		in, out := &in.ClusterUUID, &out.ClusterUUID
		*out = new(string)
		**out = **in
	}
	if in.FabricCluster != nil {
		in, out := &in.FabricCluster, &out.FabricCluster
		*out = make([]FabricClusterObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.InstanceNo != nil {
		in, out := &in.InstanceNo, &out.InstanceNo
		*out = new(string)
		**out = **in
	}
	if in.K8SVersion != nil {
		in, out := &in.K8SVersion, &out.K8SVersion
		*out = new(string)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = make([]LabelObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeCount != nil {
		in, out := &in.NodeCount, &out.NodeCount
		*out = new(float64)
		**out = **in
	}
	if in.NodePoolName != nil {
		in, out := &in.NodePoolName, &out.NodePoolName
		*out = new(string)
		**out = **in
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]NodesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProductCode != nil {
		in, out := &in.ProductCode, &out.ProductCode
		*out = new(string)
		**out = **in
	}
	if in.ServerRoleID != nil {
		in, out := &in.ServerRoleID, &out.ServerRoleID
		*out = new(string)
		**out = **in
	}
	if in.ServerSpecCode != nil {
		in, out := &in.ServerSpecCode, &out.ServerSpecCode
		*out = new(string)
		**out = **in
	}
	if in.SoftwareCode != nil {
		in, out := &in.SoftwareCode, &out.SoftwareCode
		*out = new(string)
		**out = **in
	}
	if in.StorageSize != nil {
		in, out := &in.StorageSize, &out.StorageSize
		*out = new(float64)
		**out = **in
	}
	if in.SubnetNo != nil {
		in, out := &in.SubnetNo, &out.SubnetNo
		*out = new(string)
		**out = **in
	}
	if in.SubnetNoList != nil {
		in, out := &in.SubnetNoList, &out.SubnetNoList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Taint != nil {
		in, out := &in.Taint, &out.Taint
		*out = make([]TaintObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NksNodePoolObservation.
func (in *NksNodePoolObservation) DeepCopy() *NksNodePoolObservation {
	if in == nil {
		return nil
	}
	out := new(NksNodePoolObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NksNodePoolParameters) DeepCopyInto(out *NksNodePoolParameters) {
	*out = *in
	if in.Autoscale != nil {
		in, out := &in.Autoscale, &out.Autoscale
		*out = make([]AutoscaleParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClusterUUID != nil {
		in, out := &in.ClusterUUID, &out.ClusterUUID
		*out = new(string)
		**out = **in
	}
	if in.ClusterUUIDRef != nil {
		in, out := &in.ClusterUUIDRef, &out.ClusterUUIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterUUIDSelector != nil {
		in, out := &in.ClusterUUIDSelector, &out.ClusterUUIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.FabricCluster != nil {
		in, out := &in.FabricCluster, &out.FabricCluster
		*out = make([]FabricClusterParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.K8SVersion != nil {
		in, out := &in.K8SVersion, &out.K8SVersion
		*out = new(string)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = make([]LabelParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeCount != nil {
		in, out := &in.NodeCount, &out.NodeCount
		*out = new(float64)
		**out = **in
	}
	if in.NodePoolName != nil {
		in, out := &in.NodePoolName, &out.NodePoolName
		*out = new(string)
		**out = **in
	}
	if in.ProductCode != nil {
		in, out := &in.ProductCode, &out.ProductCode
		*out = new(string)
		**out = **in
	}
	if in.ServerRoleID != nil {
		in, out := &in.ServerRoleID, &out.ServerRoleID
		*out = new(string)
		**out = **in
	}
	if in.ServerSpecCode != nil {
		in, out := &in.ServerSpecCode, &out.ServerSpecCode
		*out = new(string)
		**out = **in
	}
	if in.SoftwareCode != nil {
		in, out := &in.SoftwareCode, &out.SoftwareCode
		*out = new(string)
		**out = **in
	}
	if in.StorageSize != nil {
		in, out := &in.StorageSize, &out.StorageSize
		*out = new(float64)
		**out = **in
	}
	if in.SubnetNo != nil {
		in, out := &in.SubnetNo, &out.SubnetNo
		*out = new(string)
		**out = **in
	}
	if in.SubnetNoList != nil {
		in, out := &in.SubnetNoList, &out.SubnetNoList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Taint != nil {
		in, out := &in.Taint, &out.Taint
		*out = make([]TaintParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NksNodePoolParameters.
func (in *NksNodePoolParameters) DeepCopy() *NksNodePoolParameters {
	if in == nil {
		return nil
	}
	out := new(NksNodePoolParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NksNodePoolSpec) DeepCopyInto(out *NksNodePoolSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NksNodePoolSpec.
func (in *NksNodePoolSpec) DeepCopy() *NksNodePoolSpec {
	if in == nil {
		return nil
	}
	out := new(NksNodePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NksNodePoolStatus) DeepCopyInto(out *NksNodePoolStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NksNodePoolStatus.
func (in *NksNodePoolStatus) DeepCopy() *NksNodePoolStatus {
	if in == nil {
		return nil
	}
	out := new(NksNodePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodesInitParameters) DeepCopyInto(out *NodesInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodesInitParameters.
func (in *NodesInitParameters) DeepCopy() *NodesInitParameters {
	if in == nil {
		return nil
	}
	out := new(NodesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodesObservation) DeepCopyInto(out *NodesObservation) {
	*out = *in
	if in.ContainerVersion != nil {
		in, out := &in.ContainerVersion, &out.ContainerVersion
		*out = new(string)
		**out = **in
	}
	if in.InstanceNo != nil {
		in, out := &in.InstanceNo, &out.InstanceNo
		*out = new(float64)
		**out = **in
	}
	if in.KernelVersion != nil {
		in, out := &in.KernelVersion, &out.KernelVersion
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NodeStatus != nil {
		in, out := &in.NodeStatus, &out.NodeStatus
		*out = new(string)
		**out = **in
	}
	if in.PrivateIP != nil {
		in, out := &in.PrivateIP, &out.PrivateIP
		*out = new(string)
		**out = **in
	}
	if in.PublicIP != nil {
		in, out := &in.PublicIP, &out.PublicIP
		*out = new(string)
		**out = **in
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodesObservation.
func (in *NodesObservation) DeepCopy() *NodesObservation {
	if in == nil {
		return nil
	}
	out := new(NodesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodesParameters) DeepCopyInto(out *NodesParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodesParameters.
func (in *NodesParameters) DeepCopy() *NodesParameters {
	if in == nil {
		return nil
	}
	out := new(NodesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OidcInitParameters) DeepCopyInto(out *OidcInitParameters) {
	*out = *in
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.GroupsClaim != nil {
		in, out := &in.GroupsClaim, &out.GroupsClaim
		*out = new(string)
		**out = **in
	}
	if in.GroupsPrefix != nil {
		in, out := &in.GroupsPrefix, &out.GroupsPrefix
		*out = new(string)
		**out = **in
	}
	if in.IssuerURL != nil {
		in, out := &in.IssuerURL, &out.IssuerURL
		*out = new(string)
		**out = **in
	}
	if in.RequiredClaim != nil {
		in, out := &in.RequiredClaim, &out.RequiredClaim
		*out = new(string)
		**out = **in
	}
	if in.UsernameClaim != nil {
		in, out := &in.UsernameClaim, &out.UsernameClaim
		*out = new(string)
		**out = **in
	}
	if in.UsernamePrefix != nil {
		in, out := &in.UsernamePrefix, &out.UsernamePrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OidcInitParameters.
func (in *OidcInitParameters) DeepCopy() *OidcInitParameters {
	if in == nil {
		return nil
	}
	out := new(OidcInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OidcObservation) DeepCopyInto(out *OidcObservation) {
	*out = *in
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.GroupsClaim != nil {
		in, out := &in.GroupsClaim, &out.GroupsClaim
		*out = new(string)
		**out = **in
	}
	if in.GroupsPrefix != nil {
		in, out := &in.GroupsPrefix, &out.GroupsPrefix
		*out = new(string)
		**out = **in
	}
	if in.IssuerURL != nil {
		in, out := &in.IssuerURL, &out.IssuerURL
		*out = new(string)
		**out = **in
	}
	if in.RequiredClaim != nil {
		in, out := &in.RequiredClaim, &out.RequiredClaim
		*out = new(string)
		**out = **in
	}
	if in.UsernameClaim != nil {
		in, out := &in.UsernameClaim, &out.UsernameClaim
		*out = new(string)
		**out = **in
	}
	if in.UsernamePrefix != nil {
		in, out := &in.UsernamePrefix, &out.UsernamePrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OidcObservation.
func (in *OidcObservation) DeepCopy() *OidcObservation {
	if in == nil {
		return nil
	}
	out := new(OidcObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OidcParameters) DeepCopyInto(out *OidcParameters) {
	*out = *in
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.GroupsClaim != nil {
		in, out := &in.GroupsClaim, &out.GroupsClaim
		*out = new(string)
		**out = **in
	}
	if in.GroupsPrefix != nil {
		in, out := &in.GroupsPrefix, &out.GroupsPrefix
		*out = new(string)
		**out = **in
	}
	if in.IssuerURL != nil {
		in, out := &in.IssuerURL, &out.IssuerURL
		*out = new(string)
		**out = **in
	}
	if in.RequiredClaim != nil {
		in, out := &in.RequiredClaim, &out.RequiredClaim
		*out = new(string)
		**out = **in
	}
	if in.UsernameClaim != nil {
		in, out := &in.UsernameClaim, &out.UsernameClaim
		*out = new(string)
		**out = **in
	}
	if in.UsernamePrefix != nil {
		in, out := &in.UsernamePrefix, &out.UsernamePrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OidcParameters.
func (in *OidcParameters) DeepCopy() *OidcParameters {
	if in == nil {
		return nil
	}
	out := new(OidcParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoliciesInitParameters) DeepCopyInto(out *PoliciesInitParameters) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoliciesInitParameters.
func (in *PoliciesInitParameters) DeepCopy() *PoliciesInitParameters {
	if in == nil {
		return nil
	}
	out := new(PoliciesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoliciesObservation) DeepCopyInto(out *PoliciesObservation) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoliciesObservation.
func (in *PoliciesObservation) DeepCopy() *PoliciesObservation {
	if in == nil {
		return nil
	}
	out := new(PoliciesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoliciesParameters) DeepCopyInto(out *PoliciesParameters) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoliciesParameters.
func (in *PoliciesParameters) DeepCopy() *PoliciesParameters {
	if in == nil {
		return nil
	}
	out := new(PoliciesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaintInitParameters) DeepCopyInto(out *TaintInitParameters) {
	*out = *in
	if in.Effect != nil {
		in, out := &in.Effect, &out.Effect
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaintInitParameters.
func (in *TaintInitParameters) DeepCopy() *TaintInitParameters {
	if in == nil {
		return nil
	}
	out := new(TaintInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaintObservation) DeepCopyInto(out *TaintObservation) {
	*out = *in
	if in.Effect != nil {
		in, out := &in.Effect, &out.Effect
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaintObservation.
func (in *TaintObservation) DeepCopy() *TaintObservation {
	if in == nil {
		return nil
	}
	out := new(TaintObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaintParameters) DeepCopyInto(out *TaintParameters) {
	*out = *in
	if in.Effect != nil {
		in, out := &in.Effect, &out.Effect
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaintParameters.
func (in *TaintParameters) DeepCopy() *TaintParameters {
	if in == nil {
		return nil
	}
	out := new(TaintParameters)
	in.DeepCopyInto(out)
	return out
}
