// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AutoscaleInitParameters struct {
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	Max *float64 `json:"max,omitempty" tf:"max,omitempty"`

	Min *float64 `json:"min,omitempty" tf:"min,omitempty"`
}

type AutoscaleObservation struct {
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	Max *float64 `json:"max,omitempty" tf:"max,omitempty"`

	Min *float64 `json:"min,omitempty" tf:"min,omitempty"`
}

type AutoscaleParameters struct {

	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`

	// +kubebuilder:validation:Optional
	Max *float64 `json:"max" tf:"max,omitempty"`

	// +kubebuilder:validation:Optional
	Min *float64 `json:"min" tf:"min,omitempty"`
}

type FabricClusterInitParameters struct {

	// Name of the fabric cluster pool
	PoolName *string `json:"poolName,omitempty" tf:"pool_name,omitempty"`

	// Number of the fabric cluster pool
	PoolNo *float64 `json:"poolNo,omitempty" tf:"pool_no,omitempty"`
}

type FabricClusterObservation struct {

	// Name of the fabric cluster pool
	PoolName *string `json:"poolName,omitempty" tf:"pool_name,omitempty"`

	// Number of the fabric cluster pool
	PoolNo *float64 `json:"poolNo,omitempty" tf:"pool_no,omitempty"`
}

type FabricClusterParameters struct {

	// Name of the fabric cluster pool
	// +kubebuilder:validation:Optional
	PoolName *string `json:"poolName" tf:"pool_name,omitempty"`

	// Number of the fabric cluster pool
	// +kubebuilder:validation:Optional
	PoolNo *float64 `json:"poolNo" tf:"pool_no,omitempty"`
}

type LabelInitParameters struct {
	Key *string `json:"key,omitempty" tf:"key"`

	Value *string `json:"value,omitempty" tf:"value"`
}

type LabelObservation struct {
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type LabelParameters struct {

	// +kubebuilder:validation:Optional
	Key *string `json:"key,omitempty" tf:"key"`

	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value"`
}

type NksNodePoolInitParameters struct {
	Autoscale []AutoscaleInitParameters `json:"autoscale,omitempty" tf:"autoscale,omitempty"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/nks/v1alpha1.NksCluster
	ClusterUUID *string `json:"clusterUuid,omitempty" tf:"cluster_uuid,omitempty"`

	// Reference to a NksCluster in nks to populate clusterUuid.
	// +kubebuilder:validation:Optional
	ClusterUUIDRef *v1.NamespacedReference `json:"clusterUuidRef,omitempty" tf:"-"`

	// Selector for a NksCluster in nks to populate clusterUuid.
	// +kubebuilder:validation:Optional
	ClusterUUIDSelector *v1.NamespacedSelector `json:"clusterUuidSelector,omitempty" tf:"-"`

	// Fabric cluster pool configuration
	FabricCluster []FabricClusterInitParameters `json:"fabricCluster,omitempty" tf:"fabric_cluster,omitempty"`

	K8SVersion *string `json:"k8sVersion,omitempty" tf:"k8s_version,omitempty"`

	Label []LabelInitParameters `json:"label,omitempty" tf:"label,omitempty"`

	NodeCount *float64 `json:"nodeCount,omitempty" tf:"node_count,omitempty"`

	NodePoolName *string `json:"nodePoolName,omitempty" tf:"node_pool_name,omitempty"`

	ProductCode *string `json:"productCode,omitempty" tf:"product_code,omitempty"`

	ServerRoleID *string `json:"serverRoleId,omitempty" tf:"server_role_id,omitempty"`

	ServerSpecCode *string `json:"serverSpecCode,omitempty" tf:"server_spec_code,omitempty"`

	SoftwareCode *string `json:"softwareCode,omitempty" tf:"software_code,omitempty"`

	StorageSize *float64 `json:"storageSize,omitempty" tf:"storage_size,omitempty"`

	SubnetNo *string `json:"subnetNo,omitempty" tf:"subnet_no,omitempty"`

	SubnetNoList []*string `json:"subnetNoList,omitempty" tf:"subnet_no_list,omitempty"`

	Taint []TaintInitParameters `json:"taint,omitempty" tf:"taint,omitempty"`
}

type NksNodePoolObservation struct {
	Autoscale []AutoscaleObservation `json:"autoscale,omitempty" tf:"autoscale,omitempty"`

	ClusterUUID *string `json:"clusterUuid,omitempty" tf:"cluster_uuid,omitempty"`

	// Fabric cluster pool configuration
	FabricCluster []FabricClusterObservation `json:"fabricCluster,omitempty" tf:"fabric_cluster,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	InstanceNo *string `json:"instanceNo,omitempty" tf:"instance_no,omitempty"`

	K8SVersion *string `json:"k8sVersion,omitempty" tf:"k8s_version,omitempty"`

	Label []LabelObservation `json:"label,omitempty" tf:"label,omitempty"`

	NodeCount *float64 `json:"nodeCount,omitempty" tf:"node_count,omitempty"`

	NodePoolName *string `json:"nodePoolName,omitempty" tf:"node_pool_name,omitempty"`

	Nodes []NodesObservation `json:"nodes,omitempty" tf:"nodes,omitempty"`

	ProductCode *string `json:"productCode,omitempty" tf:"product_code,omitempty"`

	ServerRoleID *string `json:"serverRoleId,omitempty" tf:"server_role_id,omitempty"`

	ServerSpecCode *string `json:"serverSpecCode,omitempty" tf:"server_spec_code,omitempty"`

	SoftwareCode *string `json:"softwareCode,omitempty" tf:"software_code,omitempty"`

	StorageSize *float64 `json:"storageSize,omitempty" tf:"storage_size,omitempty"`

	SubnetNo *string `json:"subnetNo,omitempty" tf:"subnet_no,omitempty"`

	SubnetNoList []*string `json:"subnetNoList,omitempty" tf:"subnet_no_list,omitempty"`

	Taint []TaintObservation `json:"taint,omitempty" tf:"taint,omitempty"`
}

type NksNodePoolParameters struct {

	// +kubebuilder:validation:Optional
	Autoscale []AutoscaleParameters `json:"autoscale,omitempty" tf:"autoscale,omitempty"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/nks/v1alpha1.NksCluster
	// +kubebuilder:validation:Optional
	ClusterUUID *string `json:"clusterUuid,omitempty" tf:"cluster_uuid,omitempty"`

	// Reference to a NksCluster in nks to populate clusterUuid.
	// +kubebuilder:validation:Optional
	ClusterUUIDRef *v1.NamespacedReference `json:"clusterUuidRef,omitempty" tf:"-"`

	// Selector for a NksCluster in nks to populate clusterUuid.
	// +kubebuilder:validation:Optional
	ClusterUUIDSelector *v1.NamespacedSelector `json:"clusterUuidSelector,omitempty" tf:"-"`

	// Fabric cluster pool configuration
	// +kubebuilder:validation:Optional
	FabricCluster []FabricClusterParameters `json:"fabricCluster,omitempty" tf:"fabric_cluster,omitempty"`

	// +kubebuilder:validation:Optional
	K8SVersion *string `json:"k8sVersion,omitempty" tf:"k8s_version,omitempty"`

	// +kubebuilder:validation:Optional
	Label []LabelParameters `json:"label,omitempty" tf:"label,omitempty"`

	// +kubebuilder:validation:Optional
	NodeCount *float64 `json:"nodeCount,omitempty" tf:"node_count,omitempty"`

	// +kubebuilder:validation:Optional
	NodePoolName *string `json:"nodePoolName,omitempty" tf:"node_pool_name,omitempty"`

	// +kubebuilder:validation:Optional
	ProductCode *string `json:"productCode,omitempty" tf:"product_code,omitempty"`

	// +kubebuilder:validation:Optional
	ServerRoleID *string `json:"serverRoleId,omitempty" tf:"server_role_id,omitempty"`

	// +kubebuilder:validation:Optional
	ServerSpecCode *string `json:"serverSpecCode,omitempty" tf:"server_spec_code,omitempty"`

	// +kubebuilder:validation:Optional
	SoftwareCode *string `json:"softwareCode,omitempty" tf:"software_code,omitempty"`

	// +kubebuilder:validation:Optional
	StorageSize *float64 `json:"storageSize,omitempty" tf:"storage_size,omitempty"`

	// +kubebuilder:validation:Optional
	SubnetNo *string `json:"subnetNo,omitempty" tf:"subnet_no,omitempty"`

	// +kubebuilder:validation:Optional
	SubnetNoList []*string `json:"subnetNoList,omitempty" tf:"subnet_no_list,omitempty"`

	// +kubebuilder:validation:Optional
	Taint []TaintParameters `json:"taint,omitempty" tf:"taint,omitempty"`
}

type NodesInitParameters struct {
}

type NodesObservation struct {
	ContainerVersion *string `json:"containerVersion,omitempty" tf:"container_version,omitempty"`

	InstanceNo *float64 `json:"instanceNo,omitempty" tf:"instance_no,omitempty"`

	KernelVersion *string `json:"kernelVersion,omitempty" tf:"kernel_version,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	NodeStatus *string `json:"nodeStatus,omitempty" tf:"node_status,omitempty"`

	PrivateIP *string `json:"privateIp,omitempty" tf:"private_ip,omitempty"`

	PublicIP *string `json:"publicIp,omitempty" tf:"public_ip,omitempty"`

	Spec *string `json:"spec,omitempty" tf:"spec,omitempty"`
}

type NodesParameters struct {
}

type TaintInitParameters struct {
	Effect *string `json:"effect,omitempty" tf:"effect"`

	Key *string `json:"key,omitempty" tf:"key"`

	Value *string `json:"value,omitempty" tf:"value"`
}

type TaintObservation struct {
	Effect *string `json:"effect,omitempty" tf:"effect,omitempty"`

	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type TaintParameters struct {

	// +kubebuilder:validation:Optional
	Effect *string `json:"effect,omitempty" tf:"effect"`

	// +kubebuilder:validation:Optional
	Key *string `json:"key,omitempty" tf:"key"`

	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value"`
}

// NksNodePoolSpec defines the desired state of NksNodePool
type NksNodePoolSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            NksNodePoolParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NksNodePoolInitParameters `json:"initProvider,omitempty"`
}

// NksNodePoolStatus defines the observed state of NksNodePool.
type NksNodePoolStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NksNodePoolObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// NksNodePool is the Schema for the NksNodePools API. NAVER Cloud Platform nks node pool resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,ncloud}
type NksNodePool struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.nodePoolName) || (has(self.initProvider) && has(self.initProvider.nodePoolName))",message="spec.forProvider.nodePoolName is a required parameter"
	Spec   NksNodePoolSpec   `json:"spec"`
	Status NksNodePoolStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NksNodePoolList contains a list of NksNodePools
type NksNodePoolList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NksNodePool `json:"items"`
}

// Repository type metadata.
var (
	NksNodePool_Kind             = "NksNodePool"
	NksNodePool_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NksNodePool_Kind}.String()
	NksNodePool_KindAPIVersion   = NksNodePool_Kind + "." + CRDGroupVersion.String()
	NksNodePool_GroupVersionKind = CRDGroupVersion.WithKind(NksNodePool_Kind)
)

func init() {
	SchemeBuilder.Register(&NksNodePool{}, &NksNodePoolList{})
}
