// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type APIAllowSourcesInitParameters struct {

	// Source value: an IP address (CIDR allowed) for IP, or an instance number for VPC/VPC_SERVER.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// Type of the allowed API source.
	// +kubebuilder:validation:Enum=IP;VPC;VPC_SERVER
	// Type of the allowed API source (IP, VPC or VPC_SERVER).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type APIAllowSourcesObservation struct {

	// Source value: an IP address (CIDR allowed) for IP, or an instance number for VPC/VPC_SERVER.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// Type of the allowed API source.
	// +kubebuilder:validation:Enum=IP;VPC;VPC_SERVER
	// Type of the allowed API source (IP, VPC or VPC_SERVER).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type APIAllowSourcesParameters struct {

	// Source value: an IP address (CIDR allowed) for IP, or an instance number for VPC/VPC_SERVER.
	// +kubebuilder:validation:Optional
	Source *string `json:"source" tf:"source,omitempty"`

	// Type of the allowed API source.
	// +kubebuilder:validation:Enum=IP;VPC;VPC_SERVER
	// Type of the allowed API source (IP, VPC or VPC_SERVER).
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type SubaccountInitParameters struct {

	// Sources allowed to call APIs with this sub account's access keys. Omit to allow all.
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:XValidation:rule="self.all(x, has(x.type) && has(x.source))",message="each entry requires type and source"
	APIAllowSources []APIAllowSourcesInitParameters `json:"apiAllowSources,omitempty" tf:"api_allow_sources,omitempty"`

	// Whether the sub account can access APIs through API Gateway. Required to issue access keys.
	CanAPIGatewayAccess *bool `json:"canApiGatewayAccess,omitempty" tf:"can_api_gateway_access,omitempty"`

	// Whether the sub account can access the console. When enabled at creation, an initial password is generated and exposed once via `generated_password`.
	CanConsoleAccess *bool `json:"canConsoleAccess,omitempty" tf:"can_console_access,omitempty"`

	// IP addresses allowed to access the console. Omit to allow all.
	// +kubebuilder:validation:MinItems=1
	// List of IP addresses allowed to access the console. Omit to allow all.
	ConsolePermitIps []*string `json:"consolePermitIps,omitempty" tf:"console_permit_ips,omitempty"`

	// Email address of the sub account.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// Whether two-factor authentication is mandatory for console login.
	IsMfaMandatory *bool `json:"isMfaMandatory,omitempty" tf:"is_mfa_mandatory,omitempty"`

	// Login ID of the sub account.
	// +kubebuilder:validation:MinLength=3
	// +kubebuilder:validation:MaxLength=60
	// +kubebuilder:validation:Pattern=`^[[:alpha:]][[:alnum:].@_\x2D]*$`
	// Login ID of the sub account. Changing this creates a new sub account.
	LoginID *string `json:"loginId,omitempty" tf:"login_id,omitempty"`

	// Memo for the sub account.
	Memo *string `json:"memo,omitempty" tf:"memo,omitempty"`

	// Name of the sub account.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SubaccountObservation struct {

	// Sources allowed to call APIs with this sub account's access keys. Omit to allow all.
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:XValidation:rule="self.all(x, has(x.type) && has(x.source))",message="each entry requires type and source"
	APIAllowSources []APIAllowSourcesObservation `json:"apiAllowSources,omitempty" tf:"api_allow_sources,omitempty"`

	// Whether the sub account is active.
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// Whether the sub account can access APIs through API Gateway. Required to issue access keys.
	CanAPIGatewayAccess *bool `json:"canApiGatewayAccess,omitempty" tf:"can_api_gateway_access,omitempty"`

	// Whether the sub account can access the console. When enabled at creation, an initial password is generated and exposed once via `generated_password`.
	CanConsoleAccess *bool `json:"canConsoleAccess,omitempty" tf:"can_console_access,omitempty"`

	// IP addresses allowed to access the console. Omit to allow all.
	// +kubebuilder:validation:MinItems=1
	// List of IP addresses allowed to access the console. Omit to allow all.
	ConsolePermitIps []*string `json:"consolePermitIps,omitempty" tf:"console_permit_ips,omitempty"`

	// Creation time of the sub account.
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// Email address of the sub account.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Whether two-factor authentication is mandatory for console login.
	IsMfaMandatory *bool `json:"isMfaMandatory,omitempty" tf:"is_mfa_mandatory,omitempty"`

	// Login ID of the sub account.
	// +kubebuilder:validation:MinLength=3
	// +kubebuilder:validation:MaxLength=60
	// +kubebuilder:validation:Pattern=`^[[:alpha:]][[:alnum:].@_\x2D]*$`
	// Login ID of the sub account. Changing this creates a new sub account.
	LoginID *string `json:"loginId,omitempty" tf:"login_id,omitempty"`

	// Memo for the sub account.
	Memo *string `json:"memo,omitempty" tf:"memo,omitempty"`

	// Name of the sub account.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// NCP Resource Name of the sub account.
	Nrn *string `json:"nrn,omitempty" tf:"nrn,omitempty"`

	// Number of the sub account.
	SubAccountNo *float64 `json:"subAccountNo,omitempty" tf:"sub_account_no,omitempty"`
}

type SubaccountParameters struct {

	// Sources allowed to call APIs with this sub account's access keys. Omit to allow all.
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:XValidation:rule="self.all(x, has(x.type) && has(x.source))",message="each entry requires type and source"
	// +kubebuilder:validation:Optional
	APIAllowSources []APIAllowSourcesParameters `json:"apiAllowSources,omitempty" tf:"api_allow_sources,omitempty"`

	// Whether the sub account can access APIs through API Gateway. Required to issue access keys.
	// +kubebuilder:validation:Optional
	CanAPIGatewayAccess *bool `json:"canApiGatewayAccess,omitempty" tf:"can_api_gateway_access,omitempty"`

	// Whether the sub account can access the console. When enabled at creation, an initial password is generated and exposed once via `generated_password`.
	// +kubebuilder:validation:Optional
	CanConsoleAccess *bool `json:"canConsoleAccess,omitempty" tf:"can_console_access,omitempty"`

	// IP addresses allowed to access the console. Omit to allow all.
	// +kubebuilder:validation:MinItems=1
	// List of IP addresses allowed to access the console. Omit to allow all.
	// +kubebuilder:validation:Optional
	ConsolePermitIps []*string `json:"consolePermitIps,omitempty" tf:"console_permit_ips,omitempty"`

	// Email address of the sub account.
	// +kubebuilder:validation:Optional
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// Whether two-factor authentication is mandatory for console login.
	// +kubebuilder:validation:Optional
	IsMfaMandatory *bool `json:"isMfaMandatory,omitempty" tf:"is_mfa_mandatory,omitempty"`

	// Login ID of the sub account.
	// +kubebuilder:validation:MinLength=3
	// +kubebuilder:validation:MaxLength=60
	// +kubebuilder:validation:Pattern=`^[[:alpha:]][[:alnum:].@_\x2D]*$`
	// Login ID of the sub account. Changing this creates a new sub account.
	// +kubebuilder:validation:Optional
	LoginID *string `json:"loginId,omitempty" tf:"login_id,omitempty"`

	// Memo for the sub account.
	// +kubebuilder:validation:Optional
	Memo *string `json:"memo,omitempty" tf:"memo,omitempty"`

	// Name of the sub account.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// SubaccountSpec defines the desired state of Subaccount
type SubaccountSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SubaccountParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SubaccountInitParameters `json:"initProvider,omitempty"`
}

// SubaccountStatus defines the observed state of Subaccount.
type SubaccountStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SubaccountObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Subaccount is the Schema for the Subaccounts API. NAVER Cloud Platform sub account resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,ncloud}
type Subaccount struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.loginId) || (has(self.initProvider) && has(self.initProvider.loginId))",message="spec.forProvider.loginId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   SubaccountSpec   `json:"spec"`
	Status SubaccountStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SubaccountList contains a list of Subaccounts
type SubaccountList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Subaccount `json:"items"`
}

// Repository type metadata.
var (
	Subaccount_Kind             = "Subaccount"
	Subaccount_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Subaccount_Kind}.String()
	Subaccount_KindAPIVersion   = Subaccount_Kind + "." + CRDGroupVersion.String()
	Subaccount_GroupVersionKind = CRDGroupVersion.WithKind(Subaccount_Kind)
)

func init() {
	SchemeBuilder.Register(&Subaccount{}, &SubaccountList{})
}
