// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AccessControlGroupInitParameters struct {
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/network/v1alpha1.Vpc
	VPCNo *string `json:"vpcNo,omitempty" tf:"vpc_no,omitempty"`

	// Reference to a Vpc in network to populate vpcNo.
	// +kubebuilder:validation:Optional
	VPCNoRef *v1.NamespacedReference `json:"vpcNoRef,omitempty" tf:"-"`

	// Selector for a Vpc in network to populate vpcNo.
	// +kubebuilder:validation:Optional
	VPCNoSelector *v1.NamespacedSelector `json:"vpcNoSelector,omitempty" tf:"-"`
}

type AccessControlGroupObservation struct {
	AccessControlGroupNo *string `json:"accessControlGroupNo,omitempty" tf:"access_control_group_no,omitempty"`

	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	IsDefault *bool `json:"isDefault,omitempty" tf:"is_default,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	VPCNo *string `json:"vpcNo,omitempty" tf:"vpc_no,omitempty"`
}

type AccessControlGroupParameters struct {

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/network/v1alpha1.Vpc
	// +kubebuilder:validation:Optional
	VPCNo *string `json:"vpcNo,omitempty" tf:"vpc_no,omitempty"`

	// Reference to a Vpc in network to populate vpcNo.
	// +kubebuilder:validation:Optional
	VPCNoRef *v1.NamespacedReference `json:"vpcNoRef,omitempty" tf:"-"`

	// Selector for a Vpc in network to populate vpcNo.
	// +kubebuilder:validation:Optional
	VPCNoSelector *v1.NamespacedSelector `json:"vpcNoSelector,omitempty" tf:"-"`
}

// AccessControlGroupSpec defines the desired state of AccessControlGroup
type AccessControlGroupSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            AccessControlGroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AccessControlGroupInitParameters `json:"initProvider,omitempty"`
}

// AccessControlGroupStatus defines the observed state of AccessControlGroup.
type AccessControlGroupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AccessControlGroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AccessControlGroup is the Schema for the AccessControlGroups API. NAVER Cloud Platform access control group resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,ncloud}
type AccessControlGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AccessControlGroupSpec   `json:"spec"`
	Status            AccessControlGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccessControlGroupList contains a list of AccessControlGroups
type AccessControlGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccessControlGroup `json:"items"`
}

// Repository type metadata.
var (
	AccessControlGroup_Kind             = "AccessControlGroup"
	AccessControlGroup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccessControlGroup_Kind}.String()
	AccessControlGroup_KindAPIVersion   = AccessControlGroup_Kind + "." + CRDGroupVersion.String()
	AccessControlGroup_GroupVersionKind = CRDGroupVersion.WithKind(AccessControlGroup_Kind)
)

func init() {
	SchemeBuilder.Register(&AccessControlGroup{}, &AccessControlGroupList{})
}
