// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	v1alpha1 "github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/network/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this AccessControlGroup.
func (mg *AccessControlGroup) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.VPCNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.VPCNoRef,
		Selector:     mg.Spec.ForProvider.VPCNoSelector,
		To: reference.To{
			List:    &v1alpha1.VpcList{},
			Managed: &v1alpha1.Vpc{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VPCNo")
	}
	mg.Spec.ForProvider.VPCNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.VPCNoRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.VPCNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.VPCNoRef,
		Selector:     mg.Spec.InitProvider.VPCNoSelector,
		To: reference.To{
			List:    &v1alpha1.VpcList{},
			Managed: &v1alpha1.Vpc{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.VPCNo")
	}
	mg.Spec.InitProvider.VPCNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.VPCNoRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this AccessControlGroupRule.
func (mg *AccessControlGroupRule) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.AccessControlGroupNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AccessControlGroupNoRef,
		Selector:     mg.Spec.ForProvider.AccessControlGroupNoSelector,
		To: reference.To{
			List:    &AccessControlGroupList{},
			Managed: &AccessControlGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.AccessControlGroupNo")
	}
	mg.Spec.ForProvider.AccessControlGroupNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AccessControlGroupNoRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.AccessControlGroupNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AccessControlGroupNoRef,
		Selector:     mg.Spec.InitProvider.AccessControlGroupNoSelector,
		To: reference.To{
			List:    &AccessControlGroupList{},
			Managed: &AccessControlGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.AccessControlGroupNo")
	}
	mg.Spec.InitProvider.AccessControlGroupNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AccessControlGroupNoRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this BlockStorage.
func (mg *BlockStorage) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ServerInstanceNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ServerInstanceNoRef,
		Selector:     mg.Spec.ForProvider.ServerInstanceNoSelector,
		To: reference.To{
			List:    &ServerList{},
			Managed: &Server{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ServerInstanceNo")
	}
	mg.Spec.ForProvider.ServerInstanceNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ServerInstanceNoRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ServerInstanceNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ServerInstanceNoRef,
		Selector:     mg.Spec.InitProvider.ServerInstanceNoSelector,
		To: reference.To{
			List:    &ServerList{},
			Managed: &Server{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ServerInstanceNo")
	}
	mg.Spec.InitProvider.ServerInstanceNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ServerInstanceNoRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this BlockStorageSnapshot.
func (mg *BlockStorageSnapshot) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BlockStorageInstanceNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.BlockStorageInstanceNoRef,
		Selector:     mg.Spec.ForProvider.BlockStorageInstanceNoSelector,
		To: reference.To{
			List:    &BlockStorageList{},
			Managed: &BlockStorage{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BlockStorageInstanceNo")
	}
	mg.Spec.ForProvider.BlockStorageInstanceNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.BlockStorageInstanceNoRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.BlockStorageInstanceNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.BlockStorageInstanceNoRef,
		Selector:     mg.Spec.InitProvider.BlockStorageInstanceNoSelector,
		To: reference.To{
			List:    &BlockStorageList{},
			Managed: &BlockStorage{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.BlockStorageInstanceNo")
	}
	mg.Spec.InitProvider.BlockStorageInstanceNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.BlockStorageInstanceNoRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this LaunchConfiguration.
func (mg *LaunchConfiguration) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.LoginKeyName),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.LoginKeyNameRef,
		Selector:     mg.Spec.ForProvider.LoginKeyNameSelector,
		To: reference.To{
			List:    &LoginKeyList{},
			Managed: &LoginKey{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.LoginKeyName")
	}
	mg.Spec.ForProvider.LoginKeyName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.LoginKeyNameRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.LoginKeyName),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.LoginKeyNameRef,
		Selector:     mg.Spec.InitProvider.LoginKeyNameSelector,
		To: reference.To{
			List:    &LoginKeyList{},
			Managed: &LoginKey{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.LoginKeyName")
	}
	mg.Spec.InitProvider.LoginKeyName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.LoginKeyNameRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this NetworkInterface.
func (mg *NetworkInterface) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.AccessControlGroups),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.AccessControlGroupRefs,
		Selector:      mg.Spec.ForProvider.AccessControlGroupSelector,
		To: reference.To{
			List:    &AccessControlGroupList{},
			Managed: &AccessControlGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.AccessControlGroups")
	}
	mg.Spec.ForProvider.AccessControlGroups = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.AccessControlGroupRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ServerInstanceNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ServerInstanceNoRef,
		Selector:     mg.Spec.ForProvider.ServerInstanceNoSelector,
		To: reference.To{
			List:    &ServerList{},
			Managed: &Server{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ServerInstanceNo")
	}
	mg.Spec.ForProvider.ServerInstanceNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ServerInstanceNoRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SubnetNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.SubnetNoRef,
		Selector:     mg.Spec.ForProvider.SubnetNoSelector,
		To: reference.To{
			List:    &v1alpha1.SubnetList{},
			Managed: &v1alpha1.Subnet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SubnetNo")
	}
	mg.Spec.ForProvider.SubnetNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SubnetNoRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.AccessControlGroups),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.AccessControlGroupRefs,
		Selector:      mg.Spec.InitProvider.AccessControlGroupSelector,
		To: reference.To{
			List:    &AccessControlGroupList{},
			Managed: &AccessControlGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.AccessControlGroups")
	}
	mg.Spec.InitProvider.AccessControlGroups = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.AccessControlGroupRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ServerInstanceNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ServerInstanceNoRef,
		Selector:     mg.Spec.InitProvider.ServerInstanceNoSelector,
		To: reference.To{
			List:    &ServerList{},
			Managed: &Server{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ServerInstanceNo")
	}
	mg.Spec.InitProvider.ServerInstanceNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ServerInstanceNoRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SubnetNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.SubnetNoRef,
		Selector:     mg.Spec.InitProvider.SubnetNoSelector,
		To: reference.To{
			List:    &v1alpha1.SubnetList{},
			Managed: &v1alpha1.Subnet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SubnetNo")
	}
	mg.Spec.InitProvider.SubnetNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SubnetNoRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this PublicIP.
func (mg *PublicIP) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ServerInstanceNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ServerInstanceNoRef,
		Selector:     mg.Spec.ForProvider.ServerInstanceNoSelector,
		To: reference.To{
			List:    &ServerList{},
			Managed: &Server{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ServerInstanceNo")
	}
	mg.Spec.ForProvider.ServerInstanceNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ServerInstanceNoRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ServerInstanceNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ServerInstanceNoRef,
		Selector:     mg.Spec.InitProvider.ServerInstanceNoSelector,
		To: reference.To{
			List:    &ServerList{},
			Managed: &Server{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ServerInstanceNo")
	}
	mg.Spec.InitProvider.ServerInstanceNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ServerInstanceNoRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Server.
func (mg *Server) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.InitScriptNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.InitScriptNoRef,
		Selector:     mg.Spec.ForProvider.InitScriptNoSelector,
		To: reference.To{
			List:    &InitScriptList{},
			Managed: &InitScript{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.InitScriptNo")
	}
	mg.Spec.ForProvider.InitScriptNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.InitScriptNoRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.NetworkInterface); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.NetworkInterface[i3].NetworkInterfaceNo),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.NetworkInterface[i3].NetworkInterfaceNoRef,
			Selector:     mg.Spec.ForProvider.NetworkInterface[i3].NetworkInterfaceNoSelector,
			To: reference.To{
				List:    &NetworkInterfaceList{},
				Managed: &NetworkInterface{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.NetworkInterface[i3].NetworkInterfaceNo")
		}
		mg.Spec.ForProvider.NetworkInterface[i3].NetworkInterfaceNo = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.NetworkInterface[i3].NetworkInterfaceNoRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SubnetNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.SubnetNoRef,
		Selector:     mg.Spec.ForProvider.SubnetNoSelector,
		To: reference.To{
			List:    &v1alpha1.SubnetList{},
			Managed: &v1alpha1.Subnet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SubnetNo")
	}
	mg.Spec.ForProvider.SubnetNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SubnetNoRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.InitScriptNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.InitScriptNoRef,
		Selector:     mg.Spec.InitProvider.InitScriptNoSelector,
		To: reference.To{
			List:    &InitScriptList{},
			Managed: &InitScript{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.InitScriptNo")
	}
	mg.Spec.InitProvider.InitScriptNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.InitScriptNoRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.NetworkInterface); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.NetworkInterface[i3].NetworkInterfaceNo),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.NetworkInterface[i3].NetworkInterfaceNoRef,
			Selector:     mg.Spec.InitProvider.NetworkInterface[i3].NetworkInterfaceNoSelector,
			To: reference.To{
				List:    &NetworkInterfaceList{},
				Managed: &NetworkInterface{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.NetworkInterface[i3].NetworkInterfaceNo")
		}
		mg.Spec.InitProvider.NetworkInterface[i3].NetworkInterfaceNo = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.NetworkInterface[i3].NetworkInterfaceNoRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SubnetNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.SubnetNoRef,
		Selector:     mg.Spec.InitProvider.SubnetNoSelector,
		To: reference.To{
			List:    &v1alpha1.SubnetList{},
			Managed: &v1alpha1.Subnet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SubnetNo")
	}
	mg.Spec.InitProvider.SubnetNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SubnetNoRef = rsp.ResolvedReference

	return nil
}
