// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type NetworkInterfaceInitParameters struct {

	// References to AccessControlGroup in compute to populate accessControlGroups.
	// +kubebuilder:validation:Optional
	AccessControlGroupRefs []v1.NamespacedReference `json:"accessControlGroupRefs,omitempty" tf:"-"`

	// Selector for a list of AccessControlGroup in compute to populate accessControlGroups.
	// +kubebuilder:validation:Optional
	AccessControlGroupSelector *v1.NamespacedSelector `json:"accessControlGroupSelector,omitempty" tf:"-"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/compute/v1alpha1.AccessControlGroup
	// +crossplane:generate:reference:refFieldName=AccessControlGroupRefs
	// +crossplane:generate:reference:selectorFieldName=AccessControlGroupSelector
	// +listType=set
	AccessControlGroups []*string `json:"accessControlGroups,omitempty" tf:"access_control_groups,omitempty"`

	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	PrivateIP *string `json:"privateIp,omitempty" tf:"private_ip,omitempty"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/compute/v1alpha1.Server
	ServerInstanceNo *string `json:"serverInstanceNo,omitempty" tf:"server_instance_no,omitempty"`

	// Reference to a Server in compute to populate serverInstanceNo.
	// +kubebuilder:validation:Optional
	ServerInstanceNoRef *v1.NamespacedReference `json:"serverInstanceNoRef,omitempty" tf:"-"`

	// Selector for a Server in compute to populate serverInstanceNo.
	// +kubebuilder:validation:Optional
	ServerInstanceNoSelector *v1.NamespacedSelector `json:"serverInstanceNoSelector,omitempty" tf:"-"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/network/v1alpha1.Subnet
	SubnetNo *string `json:"subnetNo,omitempty" tf:"subnet_no,omitempty"`

	// Reference to a Subnet in network to populate subnetNo.
	// +kubebuilder:validation:Optional
	SubnetNoRef *v1.NamespacedReference `json:"subnetNoRef,omitempty" tf:"-"`

	// Selector for a Subnet in network to populate subnetNo.
	// +kubebuilder:validation:Optional
	SubnetNoSelector *v1.NamespacedSelector `json:"subnetNoSelector,omitempty" tf:"-"`
}

type NetworkInterfaceObservation struct {

	// +listType=set
	AccessControlGroups []*string `json:"accessControlGroups,omitempty" tf:"access_control_groups,omitempty"`

	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	IsDefault *bool `json:"isDefault,omitempty" tf:"is_default,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	NetworkInterfaceNo *string `json:"networkInterfaceNo,omitempty" tf:"network_interface_no,omitempty"`

	PrivateIP *string `json:"privateIp,omitempty" tf:"private_ip,omitempty"`

	ServerInstanceNo *string `json:"serverInstanceNo,omitempty" tf:"server_instance_no,omitempty"`

	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	SubnetNo *string `json:"subnetNo,omitempty" tf:"subnet_no,omitempty"`
}

type NetworkInterfaceParameters struct {

	// References to AccessControlGroup in compute to populate accessControlGroups.
	// +kubebuilder:validation:Optional
	AccessControlGroupRefs []v1.NamespacedReference `json:"accessControlGroupRefs,omitempty" tf:"-"`

	// Selector for a list of AccessControlGroup in compute to populate accessControlGroups.
	// +kubebuilder:validation:Optional
	AccessControlGroupSelector *v1.NamespacedSelector `json:"accessControlGroupSelector,omitempty" tf:"-"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/compute/v1alpha1.AccessControlGroup
	// +crossplane:generate:reference:refFieldName=AccessControlGroupRefs
	// +crossplane:generate:reference:selectorFieldName=AccessControlGroupSelector
	// +kubebuilder:validation:Optional
	// +listType=set
	AccessControlGroups []*string `json:"accessControlGroups,omitempty" tf:"access_control_groups,omitempty"`

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	PrivateIP *string `json:"privateIp,omitempty" tf:"private_ip,omitempty"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/compute/v1alpha1.Server
	// +kubebuilder:validation:Optional
	ServerInstanceNo *string `json:"serverInstanceNo,omitempty" tf:"server_instance_no,omitempty"`

	// Reference to a Server in compute to populate serverInstanceNo.
	// +kubebuilder:validation:Optional
	ServerInstanceNoRef *v1.NamespacedReference `json:"serverInstanceNoRef,omitempty" tf:"-"`

	// Selector for a Server in compute to populate serverInstanceNo.
	// +kubebuilder:validation:Optional
	ServerInstanceNoSelector *v1.NamespacedSelector `json:"serverInstanceNoSelector,omitempty" tf:"-"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/network/v1alpha1.Subnet
	// +kubebuilder:validation:Optional
	SubnetNo *string `json:"subnetNo,omitempty" tf:"subnet_no,omitempty"`

	// Reference to a Subnet in network to populate subnetNo.
	// +kubebuilder:validation:Optional
	SubnetNoRef *v1.NamespacedReference `json:"subnetNoRef,omitempty" tf:"-"`

	// Selector for a Subnet in network to populate subnetNo.
	// +kubebuilder:validation:Optional
	SubnetNoSelector *v1.NamespacedSelector `json:"subnetNoSelector,omitempty" tf:"-"`
}

// NetworkInterfaceSpec defines the desired state of NetworkInterface
type NetworkInterfaceSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            NetworkInterfaceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NetworkInterfaceInitParameters `json:"initProvider,omitempty"`
}

// NetworkInterfaceStatus defines the observed state of NetworkInterface.
type NetworkInterfaceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NetworkInterfaceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// NetworkInterface is the Schema for the NetworkInterfaces API. NAVER Cloud Platform network interface resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,ncloud}
type NetworkInterface struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              NetworkInterfaceSpec   `json:"spec"`
	Status            NetworkInterfaceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkInterfaceList contains a list of NetworkInterfaces
type NetworkInterfaceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkInterface `json:"items"`
}

// Repository type metadata.
var (
	NetworkInterface_Kind             = "NetworkInterface"
	NetworkInterface_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NetworkInterface_Kind}.String()
	NetworkInterface_KindAPIVersion   = NetworkInterface_Kind + "." + CRDGroupVersion.String()
	NetworkInterface_GroupVersionKind = CRDGroupVersion.WithKind(NetworkInterface_Kind)
)

func init() {
	SchemeBuilder.Register(&NetworkInterface{}, &NetworkInterfaceList{})
}
