//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NasVolume) DeepCopyInto(out *NasVolume) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NasVolume.
func (in *NasVolume) DeepCopy() *NasVolume {
	if in == nil {
		return nil
	}
	out := new(NasVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NasVolume) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NasVolumeInitParameters) DeepCopyInto(out *NasVolumeInitParameters) {
	*out = *in
	if in.CifsUserName != nil {
		in, out := &in.CifsUserName, &out.CifsUserName
		*out = new(string)
		**out = **in
	}
	if in.CifsUserPassword != nil {
		in, out := &in.CifsUserPassword, &out.CifsUserPassword
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.IsEncryptedVolume != nil {
		in, out := &in.IsEncryptedVolume, &out.IsEncryptedVolume
		*out = new(bool)
		**out = **in
	}
	if in.IsReturnProtection != nil {
		in, out := &in.IsReturnProtection, &out.IsReturnProtection
		*out = new(bool)
		**out = **in
	}
	if in.ServerInstanceNoList != nil {
		in, out := &in.ServerInstanceNoList, &out.ServerInstanceNoList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.VolumeAllotmentProtocolType != nil {
		in, out := &in.VolumeAllotmentProtocolType, &out.VolumeAllotmentProtocolType
		*out = new(string)
		**out = **in
	}
	if in.VolumeNamePostfix != nil {
		in, out := &in.VolumeNamePostfix, &out.VolumeNamePostfix
		*out = new(string)
		**out = **in
	}
	if in.VolumeSize != nil {
		in, out := &in.VolumeSize, &out.VolumeSize
		*out = new(float64)
		**out = **in
	}
	if in.Zone != nil {
		in, out := &in.Zone, &out.Zone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NasVolumeInitParameters.
func (in *NasVolumeInitParameters) DeepCopy() *NasVolumeInitParameters {
	if in == nil {
		return nil
	}
	out := new(NasVolumeInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NasVolumeList) DeepCopyInto(out *NasVolumeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NasVolume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NasVolumeList.
func (in *NasVolumeList) DeepCopy() *NasVolumeList {
	if in == nil {
		return nil
	}
	out := new(NasVolumeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NasVolumeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NasVolumeObservation) DeepCopyInto(out *NasVolumeObservation) {
	*out = *in
	if in.CifsUserName != nil {
		in, out := &in.CifsUserName, &out.CifsUserName
		*out = new(string)
		**out = **in
	}
	if in.CifsUserPassword != nil {
		in, out := &in.CifsUserPassword, &out.CifsUserPassword
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsEncryptedVolume != nil {
		in, out := &in.IsEncryptedVolume, &out.IsEncryptedVolume
		*out = new(bool)
		**out = **in
	}
	if in.IsEventConfiguration != nil {
		in, out := &in.IsEventConfiguration, &out.IsEventConfiguration
		*out = new(bool)
		**out = **in
	}
	if in.IsReturnProtection != nil {
		in, out := &in.IsReturnProtection, &out.IsReturnProtection
		*out = new(bool)
		**out = **in
	}
	if in.IsSnapshotConfiguration != nil {
		in, out := &in.IsSnapshotConfiguration, &out.IsSnapshotConfiguration
		*out = new(bool)
		**out = **in
	}
	if in.MountInformation != nil {
		in, out := &in.MountInformation, &out.MountInformation
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NasVolumeNo != nil {
		in, out := &in.NasVolumeNo, &out.NasVolumeNo
		*out = new(string)
		**out = **in
	}
	if in.ServerInstanceNoList != nil {
		in, out := &in.ServerInstanceNoList, &out.ServerInstanceNoList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SnapshotVolumeSize != nil {
		in, out := &in.SnapshotVolumeSize, &out.SnapshotVolumeSize
		*out = new(float64)
		**out = **in
	}
	if in.VolumeAllotmentProtocolType != nil {
		in, out := &in.VolumeAllotmentProtocolType, &out.VolumeAllotmentProtocolType
		*out = new(string)
		**out = **in
	}
	if in.VolumeNamePostfix != nil {
		in, out := &in.VolumeNamePostfix, &out.VolumeNamePostfix
		*out = new(string)
		**out = **in
	}
	if in.VolumeSize != nil {
		in, out := &in.VolumeSize, &out.VolumeSize
		*out = new(float64)
		**out = **in
	}
	if in.VolumeTotalSize != nil {
		in, out := &in.VolumeTotalSize, &out.VolumeTotalSize
		*out = new(float64)
		**out = **in
	}
	if in.Zone != nil {
		in, out := &in.Zone, &out.Zone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NasVolumeObservation.
func (in *NasVolumeObservation) DeepCopy() *NasVolumeObservation {
	if in == nil {
		return nil
	}
	out := new(NasVolumeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NasVolumeParameters) DeepCopyInto(out *NasVolumeParameters) {
	*out = *in
	if in.CifsUserName != nil {
		in, out := &in.CifsUserName, &out.CifsUserName
		*out = new(string)
		**out = **in
	}
	if in.CifsUserPassword != nil {
		in, out := &in.CifsUserPassword, &out.CifsUserPassword
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.IsEncryptedVolume != nil {
		in, out := &in.IsEncryptedVolume, &out.IsEncryptedVolume
		*out = new(bool)
		**out = **in
	}
	if in.IsReturnProtection != nil {
		in, out := &in.IsReturnProtection, &out.IsReturnProtection
		*out = new(bool)
		**out = **in
	}
	if in.ServerInstanceNoList != nil {
		in, out := &in.ServerInstanceNoList, &out.ServerInstanceNoList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.VolumeAllotmentProtocolType != nil {
		in, out := &in.VolumeAllotmentProtocolType, &out.VolumeAllotmentProtocolType
		*out = new(string)
		**out = **in
	}
	if in.VolumeNamePostfix != nil {
		in, out := &in.VolumeNamePostfix, &out.VolumeNamePostfix
		*out = new(string)
		**out = **in
	}
	if in.VolumeSize != nil {
		in, out := &in.VolumeSize, &out.VolumeSize
		*out = new(float64)
		**out = **in
	}
	if in.Zone != nil {
		in, out := &in.Zone, &out.Zone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NasVolumeParameters.
func (in *NasVolumeParameters) DeepCopy() *NasVolumeParameters {
	if in == nil {
		return nil
	}
	out := new(NasVolumeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NasVolumeSpec) DeepCopyInto(out *NasVolumeSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NasVolumeSpec.
func (in *NasVolumeSpec) DeepCopy() *NasVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(NasVolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NasVolumeStatus) DeepCopyInto(out *NasVolumeStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NasVolumeStatus.
func (in *NasVolumeStatus) DeepCopy() *NasVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(NasVolumeStatus)
	in.DeepCopyInto(out)
	return out
}
