// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Mongodb) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MongodbUsers) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Mssql) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Mysql) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MysqlDatabases) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MysqlRecovery) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MysqlSlave) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MysqlUsers) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Postgresql) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PostgresqlDatabases) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PostgresqlReadReplica) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PostgresqlUsers) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Redis) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RedisConfigGroup) Hub() {}
