// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type MysqlSlaveInitParameters struct {

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/database/v1alpha1.Mysql
	MySQLInstanceNo *string `json:"mysqlInstanceNo,omitempty" tf:"mysql_instance_no,omitempty"`

	// Reference to a Mysql in database to populate mysqlInstanceNo.
	// +kubebuilder:validation:Optional
	MySQLInstanceNoRef *v1.NamespacedReference `json:"mysqlInstanceNoRef,omitempty" tf:"-"`

	// Selector for a Mysql in database to populate mysqlInstanceNo.
	// +kubebuilder:validation:Optional
	MySQLInstanceNoSelector *v1.NamespacedSelector `json:"mysqlInstanceNoSelector,omitempty" tf:"-"`

	SubnetNo *string `json:"subnetNo,omitempty" tf:"subnet_no,omitempty"`
}

type MysqlSlaveMySQLServerListInitParameters struct {
}

type MysqlSlaveMySQLServerListObservation struct {
	CPUCount *float64 `json:"cpuCount,omitempty" tf:"cpu_count,omitempty"`

	CreateDate *string `json:"createDate,omitempty" tf:"create_date,omitempty"`

	DataStorageSize *float64 `json:"dataStorageSize,omitempty" tf:"data_storage_size,omitempty"`

	IsPublicSubnet *bool `json:"isPublicSubnet,omitempty" tf:"is_public_subnet,omitempty"`

	MemorySize *float64 `json:"memorySize,omitempty" tf:"memory_size,omitempty"`

	PrivateDomain *string `json:"privateDomain,omitempty" tf:"private_domain,omitempty"`

	ProductCode *string `json:"productCode,omitempty" tf:"product_code,omitempty"`

	PublicDomain *string `json:"publicDomain,omitempty" tf:"public_domain,omitempty"`

	ServerInstanceNo *string `json:"serverInstanceNo,omitempty" tf:"server_instance_no,omitempty"`

	ServerName *string `json:"serverName,omitempty" tf:"server_name,omitempty"`

	ServerRole *string `json:"serverRole,omitempty" tf:"server_role,omitempty"`

	SubnetNo *string `json:"subnetNo,omitempty" tf:"subnet_no,omitempty"`

	Uptime *string `json:"uptime,omitempty" tf:"uptime,omitempty"`

	UsedDataStorageSize *float64 `json:"usedDataStorageSize,omitempty" tf:"used_data_storage_size,omitempty"`

	ZoneCode *string `json:"zoneCode,omitempty" tf:"zone_code,omitempty"`
}

type MysqlSlaveMySQLServerListParameters struct {
}

type MysqlSlaveObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	MySQLInstanceNo *string `json:"mysqlInstanceNo,omitempty" tf:"mysql_instance_no,omitempty"`

	MySQLServerList []MysqlSlaveMySQLServerListObservation `json:"mysqlServerList,omitempty" tf:"mysql_server_list,omitempty"`

	SubnetNo *string `json:"subnetNo,omitempty" tf:"subnet_no,omitempty"`
}

type MysqlSlaveParameters struct {

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/database/v1alpha1.Mysql
	// +kubebuilder:validation:Optional
	MySQLInstanceNo *string `json:"mysqlInstanceNo,omitempty" tf:"mysql_instance_no,omitempty"`

	// Reference to a Mysql in database to populate mysqlInstanceNo.
	// +kubebuilder:validation:Optional
	MySQLInstanceNoRef *v1.NamespacedReference `json:"mysqlInstanceNoRef,omitempty" tf:"-"`

	// Selector for a Mysql in database to populate mysqlInstanceNo.
	// +kubebuilder:validation:Optional
	MySQLInstanceNoSelector *v1.NamespacedSelector `json:"mysqlInstanceNoSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	SubnetNo *string `json:"subnetNo,omitempty" tf:"subnet_no,omitempty"`
}

// MysqlSlaveSpec defines the desired state of MysqlSlave
type MysqlSlaveSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            MysqlSlaveParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MysqlSlaveInitParameters `json:"initProvider,omitempty"`
}

// MysqlSlaveStatus defines the observed state of MysqlSlave.
type MysqlSlaveStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MysqlSlaveObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MysqlSlave is the Schema for the MysqlSlaves API. NAVER Cloud Platform mysql slave resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,ncloud}
type MysqlSlave struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              MysqlSlaveSpec   `json:"spec"`
	Status            MysqlSlaveStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MysqlSlaveList contains a list of MysqlSlaves
type MysqlSlaveList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MysqlSlave `json:"items"`
}

// Repository type metadata.
var (
	MysqlSlave_Kind             = "MysqlSlave"
	MysqlSlave_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MysqlSlave_Kind}.String()
	MysqlSlave_KindAPIVersion   = MysqlSlave_Kind + "." + CRDGroupVersion.String()
	MysqlSlave_GroupVersionKind = CRDGroupVersion.WithKind(MysqlSlave_Kind)
)

func init() {
	SchemeBuilder.Register(&MysqlSlave{}, &MysqlSlaveList{})
}
