// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type PostgresqlInitParameters struct {

	// default: true
	AutomaticBackup *bool `json:"automaticBackup,omitempty" tf:"automatic_backup,omitempty"`

	Backup *bool `json:"backup,omitempty" tf:"backup,omitempty"`

	// default: true
	BackupFileCompression *bool `json:"backupFileCompression,omitempty" tf:"backup_file_compression,omitempty"`

	BackupFileRetentionPeriod *float64 `json:"backupFileRetentionPeriod,omitempty" tf:"backup_file_retention_period,omitempty"`

	BackupFileStorageCount *float64 `json:"backupFileStorageCount,omitempty" tf:"backup_file_storage_count,omitempty"`

	// ex) 01:15
	BackupTime *string `json:"backupTime,omitempty" tf:"backup_time,omitempty"`

	ClientCidr *string `json:"clientCidr,omitempty" tf:"client_cidr,omitempty"`

	// default: SSD
	DataStorageType *string `json:"dataStorageType,omitempty" tf:"data_storage_type,omitempty"`

	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	EngineVersionCode *string `json:"engineVersionCode,omitempty" tf:"engine_version_code,omitempty"`

	Ha *bool `json:"ha,omitempty" tf:"ha,omitempty"`

	ImageProductCode *string `json:"imageProductCode,omitempty" tf:"image_product_code,omitempty"`

	// default: false
	MultiZone *bool `json:"multiZone,omitempty" tf:"multi_zone,omitempty"`

	// default: 5432
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	ProductCode *string `json:"productCode,omitempty" tf:"product_code,omitempty"`

	SecondarySubnetNo *string `json:"secondarySubnetNo,omitempty" tf:"secondary_subnet_no,omitempty"`

	ServerNamePrefix *string `json:"serverNamePrefix,omitempty" tf:"server_name_prefix,omitempty"`

	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// default: false
	StorageEncryption *bool `json:"storageEncryption,omitempty" tf:"storage_encryption,omitempty"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/network/v1alpha1.Subnet
	SubnetNo *string `json:"subnetNo,omitempty" tf:"subnet_no,omitempty"`

	// Reference to a Subnet in network to populate subnetNo.
	// +kubebuilder:validation:Optional
	SubnetNoRef *v1.NamespacedReference `json:"subnetNoRef,omitempty" tf:"-"`

	// Selector for a Subnet in network to populate subnetNo.
	// +kubebuilder:validation:Optional
	SubnetNoSelector *v1.NamespacedSelector `json:"subnetNoSelector,omitempty" tf:"-"`

	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`

	UserPasswordSecretRef v1.LocalSecretKeySelector `json:"userPasswordSecretRef" tf:"-"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/network/v1alpha1.Vpc
	VPCNo *string `json:"vpcNo,omitempty" tf:"vpc_no,omitempty"`

	// Reference to a Vpc in network to populate vpcNo.
	// +kubebuilder:validation:Optional
	VPCNoRef *v1.NamespacedReference `json:"vpcNoRef,omitempty" tf:"-"`

	// Selector for a Vpc in network to populate vpcNo.
	// +kubebuilder:validation:Optional
	VPCNoSelector *v1.NamespacedSelector `json:"vpcNoSelector,omitempty" tf:"-"`
}

type PostgresqlObservation struct {
	AccessControlGroupNoList []*string `json:"accessControlGroupNoList,omitempty" tf:"access_control_group_no_list,omitempty"`

	// default: true
	AutomaticBackup *bool `json:"automaticBackup,omitempty" tf:"automatic_backup,omitempty"`

	Backup *bool `json:"backup,omitempty" tf:"backup,omitempty"`

	// default: true
	BackupFileCompression *bool `json:"backupFileCompression,omitempty" tf:"backup_file_compression,omitempty"`

	BackupFileRetentionPeriod *float64 `json:"backupFileRetentionPeriod,omitempty" tf:"backup_file_retention_period,omitempty"`

	BackupFileStorageCount *float64 `json:"backupFileStorageCount,omitempty" tf:"backup_file_storage_count,omitempty"`

	// ex) 01:15
	BackupTime *string `json:"backupTime,omitempty" tf:"backup_time,omitempty"`

	ClientCidr *string `json:"clientCidr,omitempty" tf:"client_cidr,omitempty"`

	// default: SSD
	DataStorageType *string `json:"dataStorageType,omitempty" tf:"data_storage_type,omitempty"`

	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	EngineVersionCode *string `json:"engineVersionCode,omitempty" tf:"engine_version_code,omitempty"`

	GenerationCode *string `json:"generationCode,omitempty" tf:"generation_code,omitempty"`

	Ha *bool `json:"ha,omitempty" tf:"ha,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	ImageProductCode *string `json:"imageProductCode,omitempty" tf:"image_product_code,omitempty"`

	// default: false
	MultiZone *bool `json:"multiZone,omitempty" tf:"multi_zone,omitempty"`

	// default: 5432
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	PostgresqlConfigList []*string `json:"postgresqlConfigList,omitempty" tf:"postgresql_config_list,omitempty"`

	PostgresqlServerList []PostgresqlServerListObservation `json:"postgresqlServerList,omitempty" tf:"postgresql_server_list,omitempty"`

	ProductCode *string `json:"productCode,omitempty" tf:"product_code,omitempty"`

	RegionCode *string `json:"regionCode,omitempty" tf:"region_code,omitempty"`

	SecondarySubnetNo *string `json:"secondarySubnetNo,omitempty" tf:"secondary_subnet_no,omitempty"`

	ServerNamePrefix *string `json:"serverNamePrefix,omitempty" tf:"server_name_prefix,omitempty"`

	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// default: false
	StorageEncryption *bool `json:"storageEncryption,omitempty" tf:"storage_encryption,omitempty"`

	SubnetNo *string `json:"subnetNo,omitempty" tf:"subnet_no,omitempty"`

	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`

	VPCNo *string `json:"vpcNo,omitempty" tf:"vpc_no,omitempty"`
}

type PostgresqlParameters struct {

	// default: true
	// +kubebuilder:validation:Optional
	AutomaticBackup *bool `json:"automaticBackup,omitempty" tf:"automatic_backup,omitempty"`

	// +kubebuilder:validation:Optional
	Backup *bool `json:"backup,omitempty" tf:"backup,omitempty"`

	// default: true
	// +kubebuilder:validation:Optional
	BackupFileCompression *bool `json:"backupFileCompression,omitempty" tf:"backup_file_compression,omitempty"`

	// +kubebuilder:validation:Optional
	BackupFileRetentionPeriod *float64 `json:"backupFileRetentionPeriod,omitempty" tf:"backup_file_retention_period,omitempty"`

	// +kubebuilder:validation:Optional
	BackupFileStorageCount *float64 `json:"backupFileStorageCount,omitempty" tf:"backup_file_storage_count,omitempty"`

	// ex) 01:15
	// +kubebuilder:validation:Optional
	BackupTime *string `json:"backupTime,omitempty" tf:"backup_time,omitempty"`

	// +kubebuilder:validation:Optional
	ClientCidr *string `json:"clientCidr,omitempty" tf:"client_cidr,omitempty"`

	// default: SSD
	// +kubebuilder:validation:Optional
	DataStorageType *string `json:"dataStorageType,omitempty" tf:"data_storage_type,omitempty"`

	// +kubebuilder:validation:Optional
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// +kubebuilder:validation:Optional
	EngineVersionCode *string `json:"engineVersionCode,omitempty" tf:"engine_version_code,omitempty"`

	// +kubebuilder:validation:Optional
	Ha *bool `json:"ha,omitempty" tf:"ha,omitempty"`

	// +kubebuilder:validation:Optional
	ImageProductCode *string `json:"imageProductCode,omitempty" tf:"image_product_code,omitempty"`

	// default: false
	// +kubebuilder:validation:Optional
	MultiZone *bool `json:"multiZone,omitempty" tf:"multi_zone,omitempty"`

	// default: 5432
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// +kubebuilder:validation:Optional
	ProductCode *string `json:"productCode,omitempty" tf:"product_code,omitempty"`

	// +kubebuilder:validation:Optional
	SecondarySubnetNo *string `json:"secondarySubnetNo,omitempty" tf:"secondary_subnet_no,omitempty"`

	// +kubebuilder:validation:Optional
	ServerNamePrefix *string `json:"serverNamePrefix,omitempty" tf:"server_name_prefix,omitempty"`

	// +kubebuilder:validation:Optional
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// default: false
	// +kubebuilder:validation:Optional
	StorageEncryption *bool `json:"storageEncryption,omitempty" tf:"storage_encryption,omitempty"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/network/v1alpha1.Subnet
	// +kubebuilder:validation:Optional
	SubnetNo *string `json:"subnetNo,omitempty" tf:"subnet_no,omitempty"`

	// Reference to a Subnet in network to populate subnetNo.
	// +kubebuilder:validation:Optional
	SubnetNoRef *v1.NamespacedReference `json:"subnetNoRef,omitempty" tf:"-"`

	// Selector for a Subnet in network to populate subnetNo.
	// +kubebuilder:validation:Optional
	SubnetNoSelector *v1.NamespacedSelector `json:"subnetNoSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`

	// +kubebuilder:validation:Optional
	UserPasswordSecretRef v1.LocalSecretKeySelector `json:"userPasswordSecretRef" tf:"-"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/network/v1alpha1.Vpc
	// +kubebuilder:validation:Optional
	VPCNo *string `json:"vpcNo,omitempty" tf:"vpc_no,omitempty"`

	// Reference to a Vpc in network to populate vpcNo.
	// +kubebuilder:validation:Optional
	VPCNoRef *v1.NamespacedReference `json:"vpcNoRef,omitempty" tf:"-"`

	// Selector for a Vpc in network to populate vpcNo.
	// +kubebuilder:validation:Optional
	VPCNoSelector *v1.NamespacedSelector `json:"vpcNoSelector,omitempty" tf:"-"`
}

type PostgresqlServerListInitParameters struct {
}

type PostgresqlServerListObservation struct {
	CPUCount *float64 `json:"cpuCount,omitempty" tf:"cpu_count,omitempty"`

	CreateDate *string `json:"createDate,omitempty" tf:"create_date,omitempty"`

	DataStorageSize *float64 `json:"dataStorageSize,omitempty" tf:"data_storage_size,omitempty"`

	MemorySize *float64 `json:"memorySize,omitempty" tf:"memory_size,omitempty"`

	PrivateDomain *string `json:"privateDomain,omitempty" tf:"private_domain,omitempty"`

	PrivateIP *string `json:"privateIp,omitempty" tf:"private_ip,omitempty"`

	ProductCode *string `json:"productCode,omitempty" tf:"product_code,omitempty"`

	PublicDomain *string `json:"publicDomain,omitempty" tf:"public_domain,omitempty"`

	PublicSubnet *bool `json:"publicSubnet,omitempty" tf:"public_subnet,omitempty"`

	ServerInstanceNo *string `json:"serverInstanceNo,omitempty" tf:"server_instance_no,omitempty"`

	ServerName *string `json:"serverName,omitempty" tf:"server_name,omitempty"`

	ServerRole *string `json:"serverRole,omitempty" tf:"server_role,omitempty"`

	SubnetNo *string `json:"subnetNo,omitempty" tf:"subnet_no,omitempty"`

	Uptime *string `json:"uptime,omitempty" tf:"uptime,omitempty"`

	UsedDataStorageSize *float64 `json:"usedDataStorageSize,omitempty" tf:"used_data_storage_size,omitempty"`

	ZoneCode *string `json:"zoneCode,omitempty" tf:"zone_code,omitempty"`
}

type PostgresqlServerListParameters struct {
}

// PostgresqlSpec defines the desired state of Postgresql
type PostgresqlSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            PostgresqlParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PostgresqlInitParameters `json:"initProvider,omitempty"`
}

// PostgresqlStatus defines the observed state of Postgresql.
type PostgresqlStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PostgresqlObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Postgresql is the Schema for the Postgresqls API. NAVER Cloud Platform postgresql resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,ncloud}
type Postgresql struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clientCidr) || (has(self.initProvider) && has(self.initProvider.clientCidr))",message="spec.forProvider.clientCidr is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.databaseName) || (has(self.initProvider) && has(self.initProvider.databaseName))",message="spec.forProvider.databaseName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serverNamePrefix) || (has(self.initProvider) && has(self.initProvider.serverNamePrefix))",message="spec.forProvider.serverNamePrefix is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceName) || (has(self.initProvider) && has(self.initProvider.serviceName))",message="spec.forProvider.serviceName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.userName) || (has(self.initProvider) && has(self.initProvider.userName))",message="spec.forProvider.userName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.userPasswordSecretRef)",message="spec.forProvider.userPasswordSecretRef is a required parameter"
	Spec   PostgresqlSpec   `json:"spec"`
	Status PostgresqlStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PostgresqlList contains a list of Postgresqls
type PostgresqlList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Postgresql `json:"items"`
}

// Repository type metadata.
var (
	Postgresql_Kind             = "Postgresql"
	Postgresql_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Postgresql_Kind}.String()
	Postgresql_KindAPIVersion   = Postgresql_Kind + "." + CRDGroupVersion.String()
	Postgresql_GroupVersionKind = CRDGroupVersion.WithKind(Postgresql_Kind)
)

func init() {
	SchemeBuilder.Register(&Postgresql{}, &PostgresqlList{})
}
