// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *NatGateway) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NetworkACL) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NetworkACLDenyAllowGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NetworkACLRule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Route) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RouteTable) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RouteTableAssociation) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Subnet) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Vpc) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VpcPeering) Hub() {}
