// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type BrokerNodesInitParameters struct {
	NodeCount *float64 `json:"nodeCount,omitempty" tf:"node_count,omitempty"`

	NodeProductCode *string `json:"nodeProductCode,omitempty" tf:"node_product_code,omitempty"`

	StorageSize *float64 `json:"storageSize,omitempty" tf:"storage_size,omitempty"`

	SubnetNo *string `json:"subnetNo,omitempty" tf:"subnet_no,omitempty"`
}

type BrokerNodesObservation struct {
	NodeCount *float64 `json:"nodeCount,omitempty" tf:"node_count,omitempty"`

	NodeProductCode *string `json:"nodeProductCode,omitempty" tf:"node_product_code,omitempty"`

	StorageSize *float64 `json:"storageSize,omitempty" tf:"storage_size,omitempty"`

	SubnetNo *string `json:"subnetNo,omitempty" tf:"subnet_no,omitempty"`
}

type BrokerNodesParameters struct {

	// +kubebuilder:validation:Optional
	NodeCount *float64 `json:"nodeCount" tf:"node_count,omitempty"`

	// +kubebuilder:validation:Optional
	NodeProductCode *string `json:"nodeProductCode" tf:"node_product_code,omitempty"`

	// +kubebuilder:validation:Optional
	StorageSize *float64 `json:"storageSize" tf:"storage_size,omitempty"`

	// +kubebuilder:validation:Optional
	SubnetNo *string `json:"subnetNo" tf:"subnet_no,omitempty"`
}

type CdssClusterInitParameters struct {
	BrokerNodes []BrokerNodesInitParameters `json:"brokerNodes,omitempty" tf:"broker_nodes,omitempty"`

	Cmak []CmakInitParameters `json:"cmak,omitempty" tf:"cmak,omitempty"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/analytics/v1alpha1.CdssConfigGroup
	ConfigGroupNo *string `json:"configGroupNo,omitempty" tf:"config_group_no,omitempty"`

	// Reference to a CdssConfigGroup in analytics to populate configGroupNo.
	// +kubebuilder:validation:Optional
	ConfigGroupNoRef *v1.NamespacedReference `json:"configGroupNoRef,omitempty" tf:"-"`

	// Selector for a CdssConfigGroup in analytics to populate configGroupNo.
	// +kubebuilder:validation:Optional
	ConfigGroupNoSelector *v1.NamespacedSelector `json:"configGroupNoSelector,omitempty" tf:"-"`

	KafkaVersionCode *string `json:"kafkaVersionCode,omitempty" tf:"kafka_version_code,omitempty"`

	ManagerNode []ManagerNodeInitParameters `json:"managerNode,omitempty" tf:"manager_node,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	OsImage *string `json:"osImage,omitempty" tf:"os_image,omitempty"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/network/v1alpha1.Vpc
	VPCNo *string `json:"vpcNo,omitempty" tf:"vpc_no,omitempty"`

	// Reference to a Vpc in network to populate vpcNo.
	// +kubebuilder:validation:Optional
	VPCNoRef *v1.NamespacedReference `json:"vpcNoRef,omitempty" tf:"-"`

	// Selector for a Vpc in network to populate vpcNo.
	// +kubebuilder:validation:Optional
	VPCNoSelector *v1.NamespacedSelector `json:"vpcNoSelector,omitempty" tf:"-"`
}

type CdssClusterObservation struct {
	BrokerNodes []BrokerNodesObservation `json:"brokerNodes,omitempty" tf:"broker_nodes,omitempty"`

	Cmak []CmakObservation `json:"cmak,omitempty" tf:"cmak,omitempty"`

	ConfigGroupNo *string `json:"configGroupNo,omitempty" tf:"config_group_no,omitempty"`

	Endpoints []EndpointsObservation `json:"endpoints,omitempty" tf:"endpoints,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	KafkaVersionCode *string `json:"kafkaVersionCode,omitempty" tf:"kafka_version_code,omitempty"`

	ManagerNode []ManagerNodeObservation `json:"managerNode,omitempty" tf:"manager_node,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	OsImage *string `json:"osImage,omitempty" tf:"os_image,omitempty"`

	VPCNo *string `json:"vpcNo,omitempty" tf:"vpc_no,omitempty"`
}

type CdssClusterParameters struct {

	// +kubebuilder:validation:Optional
	BrokerNodes []BrokerNodesParameters `json:"brokerNodes,omitempty" tf:"broker_nodes,omitempty"`

	// +kubebuilder:validation:Optional
	Cmak []CmakParameters `json:"cmak,omitempty" tf:"cmak,omitempty"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/analytics/v1alpha1.CdssConfigGroup
	// +kubebuilder:validation:Optional
	ConfigGroupNo *string `json:"configGroupNo,omitempty" tf:"config_group_no,omitempty"`

	// Reference to a CdssConfigGroup in analytics to populate configGroupNo.
	// +kubebuilder:validation:Optional
	ConfigGroupNoRef *v1.NamespacedReference `json:"configGroupNoRef,omitempty" tf:"-"`

	// Selector for a CdssConfigGroup in analytics to populate configGroupNo.
	// +kubebuilder:validation:Optional
	ConfigGroupNoSelector *v1.NamespacedSelector `json:"configGroupNoSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	KafkaVersionCode *string `json:"kafkaVersionCode,omitempty" tf:"kafka_version_code,omitempty"`

	// +kubebuilder:validation:Optional
	ManagerNode []ManagerNodeParameters `json:"managerNode,omitempty" tf:"manager_node,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	OsImage *string `json:"osImage,omitempty" tf:"os_image,omitempty"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/network/v1alpha1.Vpc
	// +kubebuilder:validation:Optional
	VPCNo *string `json:"vpcNo,omitempty" tf:"vpc_no,omitempty"`

	// Reference to a Vpc in network to populate vpcNo.
	// +kubebuilder:validation:Optional
	VPCNoRef *v1.NamespacedReference `json:"vpcNoRef,omitempty" tf:"-"`

	// Selector for a Vpc in network to populate vpcNo.
	// +kubebuilder:validation:Optional
	VPCNoSelector *v1.NamespacedSelector `json:"vpcNoSelector,omitempty" tf:"-"`
}

type CmakInitParameters struct {
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`

	UserPasswordSecretRef v1.LocalSecretKeySelector `json:"userPasswordSecretRef" tf:"-"`
}

type CmakObservation struct {
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`
}

type CmakParameters struct {

	// +kubebuilder:validation:Optional
	UserName *string `json:"userName" tf:"user_name,omitempty"`

	// +kubebuilder:validation:Optional
	UserPasswordSecretRef v1.LocalSecretKeySelector `json:"userPasswordSecretRef" tf:"-"`
}

type EndpointsInitParameters struct {
}

type EndpointsObservation struct {
	HostsPrivateEndpointTLS []*string `json:"hostsPrivateEndpointTls,omitempty" tf:"hosts_private_endpoint_tls,omitempty"`

	HostsPublicEndpointTLS []*string `json:"hostsPublicEndpointTls,omitempty" tf:"hosts_public_endpoint_tls,omitempty"`

	Plaintext []*string `json:"plaintext,omitempty" tf:"plaintext,omitempty"`

	PublicEndpointPlaintext []*string `json:"publicEndpointPlaintext,omitempty" tf:"public_endpoint_plaintext,omitempty"`

	PublicEndpointPlaintextListenerPort []*string `json:"publicEndpointPlaintextListenerPort,omitempty" tf:"public_endpoint_plaintext_listener_port,omitempty"`

	PublicEndpointTLS []*string `json:"publicEndpointTls,omitempty" tf:"public_endpoint_tls,omitempty"`

	PublicEndpointTLSListenerPort []*string `json:"publicEndpointTlsListenerPort,omitempty" tf:"public_endpoint_tls_listener_port,omitempty"`

	TLS []*string `json:"tls,omitempty" tf:"tls,omitempty"`

	Zookeeper []*string `json:"zookeeper,omitempty" tf:"zookeeper,omitempty"`
}

type EndpointsParameters struct {
}

type ManagerNodeInitParameters struct {
	NodeProductCode *string `json:"nodeProductCode,omitempty" tf:"node_product_code,omitempty"`

	SubnetNo *string `json:"subnetNo,omitempty" tf:"subnet_no,omitempty"`
}

type ManagerNodeObservation struct {
	NodeProductCode *string `json:"nodeProductCode,omitempty" tf:"node_product_code,omitempty"`

	SubnetNo *string `json:"subnetNo,omitempty" tf:"subnet_no,omitempty"`
}

type ManagerNodeParameters struct {

	// +kubebuilder:validation:Optional
	NodeProductCode *string `json:"nodeProductCode" tf:"node_product_code,omitempty"`

	// +kubebuilder:validation:Optional
	SubnetNo *string `json:"subnetNo" tf:"subnet_no,omitempty"`
}

// CdssClusterSpec defines the desired state of CdssCluster
type CdssClusterSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            CdssClusterParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CdssClusterInitParameters `json:"initProvider,omitempty"`
}

// CdssClusterStatus defines the observed state of CdssCluster.
type CdssClusterStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CdssClusterObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CdssCluster is the Schema for the CdssClusters API. NAVER Cloud Platform cdss cluster resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,ncloud}
type CdssCluster struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.brokerNodes) || (has(self.initProvider) && has(self.initProvider.brokerNodes))",message="spec.forProvider.brokerNodes is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.cmak) || (has(self.initProvider) && has(self.initProvider.cmak))",message="spec.forProvider.cmak is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.kafkaVersionCode) || (has(self.initProvider) && has(self.initProvider.kafkaVersionCode))",message="spec.forProvider.kafkaVersionCode is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.managerNode) || (has(self.initProvider) && has(self.initProvider.managerNode))",message="spec.forProvider.managerNode is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.osImage) || (has(self.initProvider) && has(self.initProvider.osImage))",message="spec.forProvider.osImage is a required parameter"
	Spec   CdssClusterSpec   `json:"spec"`
	Status CdssClusterStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CdssClusterList contains a list of CdssClusters
type CdssClusterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CdssCluster `json:"items"`
}

// Repository type metadata.
var (
	CdssCluster_Kind             = "CdssCluster"
	CdssCluster_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CdssCluster_Kind}.String()
	CdssCluster_KindAPIVersion   = CdssCluster_Kind + "." + CRDGroupVersion.String()
	CdssCluster_GroupVersionKind = CRDGroupVersion.WithKind(CdssCluster_Kind)
)

func init() {
	SchemeBuilder.Register(&CdssCluster{}, &CdssClusterList{})
}
