// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	v1alpha12 "github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/compute/v1alpha1"
	v1alpha1 "github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/network/v1alpha1"
	v1alpha11 "github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/objectstorage/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this CdssCluster.
func (mg *CdssCluster) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ConfigGroupNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ConfigGroupNoRef,
		Selector:     mg.Spec.ForProvider.ConfigGroupNoSelector,
		To: reference.To{
			List:    &CdssConfigGroupList{},
			Managed: &CdssConfigGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ConfigGroupNo")
	}
	mg.Spec.ForProvider.ConfigGroupNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ConfigGroupNoRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.VPCNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.VPCNoRef,
		Selector:     mg.Spec.ForProvider.VPCNoSelector,
		To: reference.To{
			List:    &v1alpha1.VpcList{},
			Managed: &v1alpha1.Vpc{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VPCNo")
	}
	mg.Spec.ForProvider.VPCNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.VPCNoRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ConfigGroupNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ConfigGroupNoRef,
		Selector:     mg.Spec.InitProvider.ConfigGroupNoSelector,
		To: reference.To{
			List:    &CdssConfigGroupList{},
			Managed: &CdssConfigGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ConfigGroupNo")
	}
	mg.Spec.InitProvider.ConfigGroupNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ConfigGroupNoRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.VPCNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.VPCNoRef,
		Selector:     mg.Spec.InitProvider.VPCNoSelector,
		To: reference.To{
			List:    &v1alpha1.VpcList{},
			Managed: &v1alpha1.Vpc{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.VPCNo")
	}
	mg.Spec.InitProvider.VPCNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.VPCNoRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Hadoop.
func (mg *Hadoop) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BucketName),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.BucketNameRef,
		Selector:     mg.Spec.ForProvider.BucketNameSelector,
		To: reference.To{
			List:    &v1alpha11.ObjectstorageBucketList{},
			Managed: &v1alpha11.ObjectstorageBucket{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BucketName")
	}
	mg.Spec.ForProvider.BucketName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.BucketNameRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.EdgeNodeSubnetNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.EdgeNodeSubnetNoRef,
		Selector:     mg.Spec.ForProvider.EdgeNodeSubnetNoSelector,
		To: reference.To{
			List:    &v1alpha1.SubnetList{},
			Managed: &v1alpha1.Subnet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.EdgeNodeSubnetNo")
	}
	mg.Spec.ForProvider.EdgeNodeSubnetNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.EdgeNodeSubnetNoRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.LoginKeyName),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.LoginKeyNameRef,
		Selector:     mg.Spec.ForProvider.LoginKeyNameSelector,
		To: reference.To{
			List:    &v1alpha12.LoginKeyList{},
			Managed: &v1alpha12.LoginKey{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.LoginKeyName")
	}
	mg.Spec.ForProvider.LoginKeyName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.LoginKeyNameRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.MasterNodeSubnetNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.MasterNodeSubnetNoRef,
		Selector:     mg.Spec.ForProvider.MasterNodeSubnetNoSelector,
		To: reference.To{
			List:    &v1alpha1.SubnetList{},
			Managed: &v1alpha1.Subnet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.MasterNodeSubnetNo")
	}
	mg.Spec.ForProvider.MasterNodeSubnetNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.MasterNodeSubnetNoRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.VPCNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.VPCNoRef,
		Selector:     mg.Spec.ForProvider.VPCNoSelector,
		To: reference.To{
			List:    &v1alpha1.VpcList{},
			Managed: &v1alpha1.Vpc{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VPCNo")
	}
	mg.Spec.ForProvider.VPCNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.VPCNoRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.WorkerNodeSubnetNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.WorkerNodeSubnetNoRef,
		Selector:     mg.Spec.ForProvider.WorkerNodeSubnetNoSelector,
		To: reference.To{
			List:    &v1alpha1.SubnetList{},
			Managed: &v1alpha1.Subnet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.WorkerNodeSubnetNo")
	}
	mg.Spec.ForProvider.WorkerNodeSubnetNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.WorkerNodeSubnetNoRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.BucketName),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.BucketNameRef,
		Selector:     mg.Spec.InitProvider.BucketNameSelector,
		To: reference.To{
			List:    &v1alpha11.ObjectstorageBucketList{},
			Managed: &v1alpha11.ObjectstorageBucket{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.BucketName")
	}
	mg.Spec.InitProvider.BucketName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.BucketNameRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.EdgeNodeSubnetNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.EdgeNodeSubnetNoRef,
		Selector:     mg.Spec.InitProvider.EdgeNodeSubnetNoSelector,
		To: reference.To{
			List:    &v1alpha1.SubnetList{},
			Managed: &v1alpha1.Subnet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.EdgeNodeSubnetNo")
	}
	mg.Spec.InitProvider.EdgeNodeSubnetNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.EdgeNodeSubnetNoRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.LoginKeyName),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.LoginKeyNameRef,
		Selector:     mg.Spec.InitProvider.LoginKeyNameSelector,
		To: reference.To{
			List:    &v1alpha12.LoginKeyList{},
			Managed: &v1alpha12.LoginKey{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.LoginKeyName")
	}
	mg.Spec.InitProvider.LoginKeyName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.LoginKeyNameRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.MasterNodeSubnetNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.MasterNodeSubnetNoRef,
		Selector:     mg.Spec.InitProvider.MasterNodeSubnetNoSelector,
		To: reference.To{
			List:    &v1alpha1.SubnetList{},
			Managed: &v1alpha1.Subnet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.MasterNodeSubnetNo")
	}
	mg.Spec.InitProvider.MasterNodeSubnetNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.MasterNodeSubnetNoRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.VPCNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.VPCNoRef,
		Selector:     mg.Spec.InitProvider.VPCNoSelector,
		To: reference.To{
			List:    &v1alpha1.VpcList{},
			Managed: &v1alpha1.Vpc{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.VPCNo")
	}
	mg.Spec.InitProvider.VPCNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.VPCNoRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.WorkerNodeSubnetNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.WorkerNodeSubnetNoRef,
		Selector:     mg.Spec.InitProvider.WorkerNodeSubnetNoSelector,
		To: reference.To{
			List:    &v1alpha1.SubnetList{},
			Managed: &v1alpha1.Subnet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.WorkerNodeSubnetNo")
	}
	mg.Spec.InitProvider.WorkerNodeSubnetNo = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.WorkerNodeSubnetNoRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this SesCluster.
func (mg *SesCluster) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.LoginKeyName),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.LoginKeyNameRef,
		Selector:     mg.Spec.ForProvider.LoginKeyNameSelector,
		To: reference.To{
			List:    &v1alpha12.LoginKeyList{},
			Managed: &v1alpha12.LoginKey{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.LoginKeyName")
	}
	mg.Spec.ForProvider.LoginKeyName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.LoginKeyNameRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.VPCNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.VPCNoRef,
		Selector:     mg.Spec.ForProvider.VPCNoSelector,
		To: reference.To{
			List:    &v1alpha1.VpcList{},
			Managed: &v1alpha1.Vpc{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VPCNo")
	}
	mg.Spec.ForProvider.VPCNo = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.VPCNoRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.LoginKeyName),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.LoginKeyNameRef,
		Selector:     mg.Spec.InitProvider.LoginKeyNameSelector,
		To: reference.To{
			List:    &v1alpha12.LoginKeyList{},
			Managed: &v1alpha12.LoginKey{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.LoginKeyName")
	}
	mg.Spec.InitProvider.LoginKeyName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.LoginKeyNameRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.VPCNo),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.VPCNoRef,
		Selector:     mg.Spec.InitProvider.VPCNoSelector,
		To: reference.To{
			List:    &v1alpha1.VpcList{},
			Managed: &v1alpha1.Vpc{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.VPCNo")
	}
	mg.Spec.InitProvider.VPCNo = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.VPCNoRef = rsp.ResolvedReference

	return nil
}
