// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type HadoopInitParameters struct {

	// this attribute can used over 1.5 version
	AddOnCodeList []*string `json:"addOnCodeList,omitempty" tf:"add_on_code_list,omitempty"`

	AdminUserName *string `json:"adminUserName,omitempty" tf:"admin_user_name,omitempty"`

	AdminUserPasswordSecretRef v1.LocalSecretKeySelector `json:"adminUserPasswordSecretRef" tf:"-"`

	BootstrapScript *string `json:"bootstrapScript,omitempty" tf:"bootstrap_script,omitempty"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/objectstorage/v1alpha1.ObjectstorageBucket
	BucketName *string `json:"bucketName,omitempty" tf:"bucket_name,omitempty"`

	// Reference to a ObjectstorageBucket in objectstorage to populate bucketName.
	// +kubebuilder:validation:Optional
	BucketNameRef *v1.NamespacedReference `json:"bucketNameRef,omitempty" tf:"-"`

	// Selector for a ObjectstorageBucket in objectstorage to populate bucketName.
	// +kubebuilder:validation:Optional
	BucketNameSelector *v1.NamespacedSelector `json:"bucketNameSelector,omitempty" tf:"-"`

	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	ClusterTypeCode *string `json:"clusterTypeCode,omitempty" tf:"cluster_type_code,omitempty"`

	// default: minimum spec
	EdgeNodeProductCode *string `json:"edgeNodeProductCode,omitempty" tf:"edge_node_product_code,omitempty"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/network/v1alpha1.Subnet
	EdgeNodeSubnetNo *string `json:"edgeNodeSubnetNo,omitempty" tf:"edge_node_subnet_no,omitempty"`

	// Reference to a Subnet in network to populate edgeNodeSubnetNo.
	// +kubebuilder:validation:Optional
	EdgeNodeSubnetNoRef *v1.NamespacedReference `json:"edgeNodeSubnetNoRef,omitempty" tf:"-"`

	// Selector for a Subnet in network to populate edgeNodeSubnetNo.
	// +kubebuilder:validation:Optional
	EdgeNodeSubnetNoSelector *v1.NamespacedSelector `json:"edgeNodeSubnetNoSelector,omitempty" tf:"-"`

	EngineVersionCode *string `json:"engineVersionCode,omitempty" tf:"engine_version_code,omitempty"`

	// default: latest version
	ImageProductCode *string `json:"imageProductCode,omitempty" tf:"image_product_code,omitempty"`

	KdcPasswordSecretRef *v1.LocalSecretKeySelector `json:"kdcPasswordSecretRef,omitempty" tf:"-"`

	KdcRealm *string `json:"kdcRealm,omitempty" tf:"kdc_realm,omitempty"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/compute/v1alpha1.LoginKey
	LoginKeyName *string `json:"loginKeyName,omitempty" tf:"login_key_name,omitempty"`

	// Reference to a LoginKey in compute to populate loginKeyName.
	// +kubebuilder:validation:Optional
	LoginKeyNameRef *v1.NamespacedReference `json:"loginKeyNameRef,omitempty" tf:"-"`

	// Selector for a LoginKey in compute to populate loginKeyName.
	// +kubebuilder:validation:Optional
	LoginKeyNameSelector *v1.NamespacedSelector `json:"loginKeyNameSelector,omitempty" tf:"-"`

	MasterNodeDataStorageSize *float64 `json:"masterNodeDataStorageSize,omitempty" tf:"master_node_data_storage_size,omitempty"`

	// default: SSD
	MasterNodeDataStorageType *string `json:"masterNodeDataStorageType,omitempty" tf:"master_node_data_storage_type,omitempty"`

	// default: minimum spec
	MasterNodeProductCode *string `json:"masterNodeProductCode,omitempty" tf:"master_node_product_code,omitempty"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/network/v1alpha1.Subnet
	MasterNodeSubnetNo *string `json:"masterNodeSubnetNo,omitempty" tf:"master_node_subnet_no,omitempty"`

	// Reference to a Subnet in network to populate masterNodeSubnetNo.
	// +kubebuilder:validation:Optional
	MasterNodeSubnetNoRef *v1.NamespacedReference `json:"masterNodeSubnetNoRef,omitempty" tf:"-"`

	// Selector for a Subnet in network to populate masterNodeSubnetNo.
	// +kubebuilder:validation:Optional
	MasterNodeSubnetNoSelector *v1.NamespacedSelector `json:"masterNodeSubnetNoSelector,omitempty" tf:"-"`

	// default: false
	UseBootstrapScript *bool `json:"useBootstrapScript,omitempty" tf:"use_bootstrap_script,omitempty"`

	// this attribute can used over 2.0 version
	UseDataCatalog *bool `json:"useDataCatalog,omitempty" tf:"use_data_catalog,omitempty"`

	UseKdc *bool `json:"useKdc,omitempty" tf:"use_kdc,omitempty"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/network/v1alpha1.Vpc
	VPCNo *string `json:"vpcNo,omitempty" tf:"vpc_no,omitempty"`

	// Reference to a Vpc in network to populate vpcNo.
	// +kubebuilder:validation:Optional
	VPCNoRef *v1.NamespacedReference `json:"vpcNoRef,omitempty" tf:"-"`

	// Selector for a Vpc in network to populate vpcNo.
	// +kubebuilder:validation:Optional
	VPCNoSelector *v1.NamespacedSelector `json:"vpcNoSelector,omitempty" tf:"-"`

	WorkerNodeCount *float64 `json:"workerNodeCount,omitempty" tf:"worker_node_count,omitempty"`

	WorkerNodeDataStorageSize *float64 `json:"workerNodeDataStorageSize,omitempty" tf:"worker_node_data_storage_size,omitempty"`

	// default: SSD
	WorkerNodeDataStorageType *string `json:"workerNodeDataStorageType,omitempty" tf:"worker_node_data_storage_type,omitempty"`

	// default: minimum spec
	WorkerNodeProductCode *string `json:"workerNodeProductCode,omitempty" tf:"worker_node_product_code,omitempty"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/network/v1alpha1.Subnet
	WorkerNodeSubnetNo *string `json:"workerNodeSubnetNo,omitempty" tf:"worker_node_subnet_no,omitempty"`

	// Reference to a Subnet in network to populate workerNodeSubnetNo.
	// +kubebuilder:validation:Optional
	WorkerNodeSubnetNoRef *v1.NamespacedReference `json:"workerNodeSubnetNoRef,omitempty" tf:"-"`

	// Selector for a Subnet in network to populate workerNodeSubnetNo.
	// +kubebuilder:validation:Optional
	WorkerNodeSubnetNoSelector *v1.NamespacedSelector `json:"workerNodeSubnetNoSelector,omitempty" tf:"-"`
}

type HadoopObservation struct {
	AccessControlGroupNoList []*string `json:"accessControlGroupNoList,omitempty" tf:"access_control_group_no_list,omitempty"`

	// this attribute can used over 1.5 version
	AddOnCodeList []*string `json:"addOnCodeList,omitempty" tf:"add_on_code_list,omitempty"`

	AdminUserName *string `json:"adminUserName,omitempty" tf:"admin_user_name,omitempty"`

	AmbariServerHost *string `json:"ambariServerHost,omitempty" tf:"ambari_server_host,omitempty"`

	BootstrapScript *string `json:"bootstrapScript,omitempty" tf:"bootstrap_script,omitempty"`

	BucketName *string `json:"bucketName,omitempty" tf:"bucket_name,omitempty"`

	ClusterDirectAccessAccount *string `json:"clusterDirectAccessAccount,omitempty" tf:"cluster_direct_access_account,omitempty"`

	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	ClusterTypeCode *string `json:"clusterTypeCode,omitempty" tf:"cluster_type_code,omitempty"`

	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// default: minimum spec
	EdgeNodeProductCode *string `json:"edgeNodeProductCode,omitempty" tf:"edge_node_product_code,omitempty"`

	EdgeNodeSubnetNo *string `json:"edgeNodeSubnetNo,omitempty" tf:"edge_node_subnet_no,omitempty"`

	EngineVersionCode *string `json:"engineVersionCode,omitempty" tf:"engine_version_code,omitempty"`

	HadoopServerList []HadoopServerListObservation `json:"hadoopServerList,omitempty" tf:"hadoop_server_list,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// default: latest version
	ImageProductCode *string `json:"imageProductCode,omitempty" tf:"image_product_code,omitempty"`

	IsHa *bool `json:"isHa,omitempty" tf:"is_ha,omitempty"`

	KdcRealm *string `json:"kdcRealm,omitempty" tf:"kdc_realm,omitempty"`

	LoginKeyName *string `json:"loginKeyName,omitempty" tf:"login_key_name,omitempty"`

	MasterNodeDataStorageSize *float64 `json:"masterNodeDataStorageSize,omitempty" tf:"master_node_data_storage_size,omitempty"`

	// default: SSD
	MasterNodeDataStorageType *string `json:"masterNodeDataStorageType,omitempty" tf:"master_node_data_storage_type,omitempty"`

	// default: minimum spec
	MasterNodeProductCode *string `json:"masterNodeProductCode,omitempty" tf:"master_node_product_code,omitempty"`

	MasterNodeSubnetNo *string `json:"masterNodeSubnetNo,omitempty" tf:"master_node_subnet_no,omitempty"`

	RegionCode *string `json:"regionCode,omitempty" tf:"region_code,omitempty"`

	// default: false
	UseBootstrapScript *bool `json:"useBootstrapScript,omitempty" tf:"use_bootstrap_script,omitempty"`

	// this attribute can used over 2.0 version
	UseDataCatalog *bool `json:"useDataCatalog,omitempty" tf:"use_data_catalog,omitempty"`

	UseKdc *bool `json:"useKdc,omitempty" tf:"use_kdc,omitempty"`

	VPCNo *string `json:"vpcNo,omitempty" tf:"vpc_no,omitempty"`

	WorkerNodeCount *float64 `json:"workerNodeCount,omitempty" tf:"worker_node_count,omitempty"`

	WorkerNodeDataStorageSize *float64 `json:"workerNodeDataStorageSize,omitempty" tf:"worker_node_data_storage_size,omitempty"`

	// default: SSD
	WorkerNodeDataStorageType *string `json:"workerNodeDataStorageType,omitempty" tf:"worker_node_data_storage_type,omitempty"`

	// default: minimum spec
	WorkerNodeProductCode *string `json:"workerNodeProductCode,omitempty" tf:"worker_node_product_code,omitempty"`

	WorkerNodeSubnetNo *string `json:"workerNodeSubnetNo,omitempty" tf:"worker_node_subnet_no,omitempty"`
}

type HadoopParameters struct {

	// this attribute can used over 1.5 version
	// +kubebuilder:validation:Optional
	AddOnCodeList []*string `json:"addOnCodeList,omitempty" tf:"add_on_code_list,omitempty"`

	// +kubebuilder:validation:Optional
	AdminUserName *string `json:"adminUserName,omitempty" tf:"admin_user_name,omitempty"`

	// +kubebuilder:validation:Optional
	AdminUserPasswordSecretRef v1.LocalSecretKeySelector `json:"adminUserPasswordSecretRef" tf:"-"`

	// +kubebuilder:validation:Optional
	BootstrapScript *string `json:"bootstrapScript,omitempty" tf:"bootstrap_script,omitempty"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/objectstorage/v1alpha1.ObjectstorageBucket
	// +kubebuilder:validation:Optional
	BucketName *string `json:"bucketName,omitempty" tf:"bucket_name,omitempty"`

	// Reference to a ObjectstorageBucket in objectstorage to populate bucketName.
	// +kubebuilder:validation:Optional
	BucketNameRef *v1.NamespacedReference `json:"bucketNameRef,omitempty" tf:"-"`

	// Selector for a ObjectstorageBucket in objectstorage to populate bucketName.
	// +kubebuilder:validation:Optional
	BucketNameSelector *v1.NamespacedSelector `json:"bucketNameSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// +kubebuilder:validation:Optional
	ClusterTypeCode *string `json:"clusterTypeCode,omitempty" tf:"cluster_type_code,omitempty"`

	// default: minimum spec
	// +kubebuilder:validation:Optional
	EdgeNodeProductCode *string `json:"edgeNodeProductCode,omitempty" tf:"edge_node_product_code,omitempty"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/network/v1alpha1.Subnet
	// +kubebuilder:validation:Optional
	EdgeNodeSubnetNo *string `json:"edgeNodeSubnetNo,omitempty" tf:"edge_node_subnet_no,omitempty"`

	// Reference to a Subnet in network to populate edgeNodeSubnetNo.
	// +kubebuilder:validation:Optional
	EdgeNodeSubnetNoRef *v1.NamespacedReference `json:"edgeNodeSubnetNoRef,omitempty" tf:"-"`

	// Selector for a Subnet in network to populate edgeNodeSubnetNo.
	// +kubebuilder:validation:Optional
	EdgeNodeSubnetNoSelector *v1.NamespacedSelector `json:"edgeNodeSubnetNoSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	EngineVersionCode *string `json:"engineVersionCode,omitempty" tf:"engine_version_code,omitempty"`

	// default: latest version
	// +kubebuilder:validation:Optional
	ImageProductCode *string `json:"imageProductCode,omitempty" tf:"image_product_code,omitempty"`

	// +kubebuilder:validation:Optional
	KdcPasswordSecretRef *v1.LocalSecretKeySelector `json:"kdcPasswordSecretRef,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	KdcRealm *string `json:"kdcRealm,omitempty" tf:"kdc_realm,omitempty"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/compute/v1alpha1.LoginKey
	// +kubebuilder:validation:Optional
	LoginKeyName *string `json:"loginKeyName,omitempty" tf:"login_key_name,omitempty"`

	// Reference to a LoginKey in compute to populate loginKeyName.
	// +kubebuilder:validation:Optional
	LoginKeyNameRef *v1.NamespacedReference `json:"loginKeyNameRef,omitempty" tf:"-"`

	// Selector for a LoginKey in compute to populate loginKeyName.
	// +kubebuilder:validation:Optional
	LoginKeyNameSelector *v1.NamespacedSelector `json:"loginKeyNameSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	MasterNodeDataStorageSize *float64 `json:"masterNodeDataStorageSize,omitempty" tf:"master_node_data_storage_size,omitempty"`

	// default: SSD
	// +kubebuilder:validation:Optional
	MasterNodeDataStorageType *string `json:"masterNodeDataStorageType,omitempty" tf:"master_node_data_storage_type,omitempty"`

	// default: minimum spec
	// +kubebuilder:validation:Optional
	MasterNodeProductCode *string `json:"masterNodeProductCode,omitempty" tf:"master_node_product_code,omitempty"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/network/v1alpha1.Subnet
	// +kubebuilder:validation:Optional
	MasterNodeSubnetNo *string `json:"masterNodeSubnetNo,omitempty" tf:"master_node_subnet_no,omitempty"`

	// Reference to a Subnet in network to populate masterNodeSubnetNo.
	// +kubebuilder:validation:Optional
	MasterNodeSubnetNoRef *v1.NamespacedReference `json:"masterNodeSubnetNoRef,omitempty" tf:"-"`

	// Selector for a Subnet in network to populate masterNodeSubnetNo.
	// +kubebuilder:validation:Optional
	MasterNodeSubnetNoSelector *v1.NamespacedSelector `json:"masterNodeSubnetNoSelector,omitempty" tf:"-"`

	// default: false
	// +kubebuilder:validation:Optional
	UseBootstrapScript *bool `json:"useBootstrapScript,omitempty" tf:"use_bootstrap_script,omitempty"`

	// this attribute can used over 2.0 version
	// +kubebuilder:validation:Optional
	UseDataCatalog *bool `json:"useDataCatalog,omitempty" tf:"use_data_catalog,omitempty"`

	// +kubebuilder:validation:Optional
	UseKdc *bool `json:"useKdc,omitempty" tf:"use_kdc,omitempty"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/network/v1alpha1.Vpc
	// +kubebuilder:validation:Optional
	VPCNo *string `json:"vpcNo,omitempty" tf:"vpc_no,omitempty"`

	// Reference to a Vpc in network to populate vpcNo.
	// +kubebuilder:validation:Optional
	VPCNoRef *v1.NamespacedReference `json:"vpcNoRef,omitempty" tf:"-"`

	// Selector for a Vpc in network to populate vpcNo.
	// +kubebuilder:validation:Optional
	VPCNoSelector *v1.NamespacedSelector `json:"vpcNoSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	WorkerNodeCount *float64 `json:"workerNodeCount,omitempty" tf:"worker_node_count,omitempty"`

	// +kubebuilder:validation:Optional
	WorkerNodeDataStorageSize *float64 `json:"workerNodeDataStorageSize,omitempty" tf:"worker_node_data_storage_size,omitempty"`

	// default: SSD
	// +kubebuilder:validation:Optional
	WorkerNodeDataStorageType *string `json:"workerNodeDataStorageType,omitempty" tf:"worker_node_data_storage_type,omitempty"`

	// default: minimum spec
	// +kubebuilder:validation:Optional
	WorkerNodeProductCode *string `json:"workerNodeProductCode,omitempty" tf:"worker_node_product_code,omitempty"`

	// +crossplane:generate:reference:type=github.com/mrchypark/crossplane-provider-ncloud/apis/namespaced/network/v1alpha1.Subnet
	// +kubebuilder:validation:Optional
	WorkerNodeSubnetNo *string `json:"workerNodeSubnetNo,omitempty" tf:"worker_node_subnet_no,omitempty"`

	// Reference to a Subnet in network to populate workerNodeSubnetNo.
	// +kubebuilder:validation:Optional
	WorkerNodeSubnetNoRef *v1.NamespacedReference `json:"workerNodeSubnetNoRef,omitempty" tf:"-"`

	// Selector for a Subnet in network to populate workerNodeSubnetNo.
	// +kubebuilder:validation:Optional
	WorkerNodeSubnetNoSelector *v1.NamespacedSelector `json:"workerNodeSubnetNoSelector,omitempty" tf:"-"`
}

type HadoopServerListInitParameters struct {
}

type HadoopServerListObservation struct {
	CPUCount *float64 `json:"cpuCount,omitempty" tf:"cpu_count,omitempty"`

	CreateDate *string `json:"createDate,omitempty" tf:"create_date,omitempty"`

	DataStorageSize *float64 `json:"dataStorageSize,omitempty" tf:"data_storage_size,omitempty"`

	DataStorageType *string `json:"dataStorageType,omitempty" tf:"data_storage_type,omitempty"`

	IsPublicSubnet *bool `json:"isPublicSubnet,omitempty" tf:"is_public_subnet,omitempty"`

	MemorySize *float64 `json:"memorySize,omitempty" tf:"memory_size,omitempty"`

	ProductCode *string `json:"productCode,omitempty" tf:"product_code,omitempty"`

	ServerInstanceNo *string `json:"serverInstanceNo,omitempty" tf:"server_instance_no,omitempty"`

	ServerName *string `json:"serverName,omitempty" tf:"server_name,omitempty"`

	ServerRole *string `json:"serverRole,omitempty" tf:"server_role,omitempty"`

	SubnetNo *string `json:"subnetNo,omitempty" tf:"subnet_no,omitempty"`

	Uptime *string `json:"uptime,omitempty" tf:"uptime,omitempty"`

	ZoneCode *string `json:"zoneCode,omitempty" tf:"zone_code,omitempty"`
}

type HadoopServerListParameters struct {
}

// HadoopSpec defines the desired state of Hadoop
type HadoopSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            HadoopParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider HadoopInitParameters `json:"initProvider,omitempty"`
}

// HadoopStatus defines the observed state of Hadoop.
type HadoopStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        HadoopObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Hadoop is the Schema for the Hadoops API. NAVER Cloud Platform hadoop resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,ncloud}
type Hadoop struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.adminUserName) || (has(self.initProvider) && has(self.initProvider.adminUserName))",message="spec.forProvider.adminUserName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.adminUserPasswordSecretRef)",message="spec.forProvider.adminUserPasswordSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clusterName) || (has(self.initProvider) && has(self.initProvider.clusterName))",message="spec.forProvider.clusterName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clusterTypeCode) || (has(self.initProvider) && has(self.initProvider.clusterTypeCode))",message="spec.forProvider.clusterTypeCode is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.masterNodeDataStorageSize) || (has(self.initProvider) && has(self.initProvider.masterNodeDataStorageSize))",message="spec.forProvider.masterNodeDataStorageSize is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.masterNodeDataStorageType) || (has(self.initProvider) && has(self.initProvider.masterNodeDataStorageType))",message="spec.forProvider.masterNodeDataStorageType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.workerNodeDataStorageSize) || (has(self.initProvider) && has(self.initProvider.workerNodeDataStorageSize))",message="spec.forProvider.workerNodeDataStorageSize is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.workerNodeDataStorageType) || (has(self.initProvider) && has(self.initProvider.workerNodeDataStorageType))",message="spec.forProvider.workerNodeDataStorageType is a required parameter"
	Spec   HadoopSpec   `json:"spec"`
	Status HadoopStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// HadoopList contains a list of Hadoops
type HadoopList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Hadoop `json:"items"`
}

// Repository type metadata.
var (
	Hadoop_Kind             = "Hadoop"
	Hadoop_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Hadoop_Kind}.String()
	Hadoop_KindAPIVersion   = Hadoop_Kind + "." + CRDGroupVersion.String()
	Hadoop_GroupVersionKind = CRDGroupVersion.WithKind(Hadoop_Kind)
)

func init() {
	SchemeBuilder.Register(&Hadoop{}, &HadoopList{})
}
