// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type SourcecommitRepositoryInitParameters struct {
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	FileSafer *bool `json:"fileSafer,omitempty" tf:"file_safer,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SourcecommitRepositoryObservation struct {
	Creator *string `json:"creator,omitempty" tf:"creator,omitempty"`

	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	FileSafer *bool `json:"fileSafer,omitempty" tf:"file_safer,omitempty"`

	GitHTTPSURL *string `json:"gitHttpsUrl,omitempty" tf:"git_https_url,omitempty"`

	GitSSHURL *string `json:"gitSshUrl,omitempty" tf:"git_ssh_url,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	RepositoryNo *string `json:"repositoryNo,omitempty" tf:"repository_no,omitempty"`
}

type SourcecommitRepositoryParameters struct {

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +kubebuilder:validation:Optional
	FileSafer *bool `json:"fileSafer,omitempty" tf:"file_safer,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// SourcecommitRepositorySpec defines the desired state of SourcecommitRepository
type SourcecommitRepositorySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SourcecommitRepositoryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SourcecommitRepositoryInitParameters `json:"initProvider,omitempty"`
}

// SourcecommitRepositoryStatus defines the observed state of SourcecommitRepository.
type SourcecommitRepositoryStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SourcecommitRepositoryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SourcecommitRepository is the Schema for the SourcecommitRepositorys API. NAVER Cloud Platform sourcecommit repository resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,ncloud}
type SourcecommitRepository struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   SourcecommitRepositorySpec   `json:"spec"`
	Status SourcecommitRepositoryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SourcecommitRepositoryList contains a list of SourcecommitRepositorys
type SourcecommitRepositoryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SourcecommitRepository `json:"items"`
}

// Repository type metadata.
var (
	SourcecommitRepository_Kind             = "SourcecommitRepository"
	SourcecommitRepository_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SourcecommitRepository_Kind}.String()
	SourcecommitRepository_KindAPIVersion   = SourcecommitRepository_Kind + "." + CRDGroupVersion.String()
	SourcecommitRepository_GroupVersionKind = CRDGroupVersion.WithKind(SourcecommitRepository_Kind)
)

func init() {
	SchemeBuilder.Register(&SourcecommitRepository{}, &SourcecommitRepositoryList{})
}
