//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckInitParameters) DeepCopyInto(out *HealthCheckInitParameters) {
	*out = *in
	if in.Cycle != nil {
		in, out := &in.Cycle, &out.Cycle
		*out = new(float64)
		**out = **in
	}
	if in.DownThreshold != nil {
		in, out := &in.DownThreshold, &out.DownThreshold
		*out = new(float64)
		**out = **in
	}
	if in.HTTPMethod != nil {
		in, out := &in.HTTPMethod, &out.HTTPMethod
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.URLPath != nil {
		in, out := &in.URLPath, &out.URLPath
		*out = new(string)
		**out = **in
	}
	if in.UpThreshold != nil {
		in, out := &in.UpThreshold, &out.UpThreshold
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckInitParameters.
func (in *HealthCheckInitParameters) DeepCopy() *HealthCheckInitParameters {
	if in == nil {
		return nil
	}
	out := new(HealthCheckInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckObservation) DeepCopyInto(out *HealthCheckObservation) {
	*out = *in
	if in.Cycle != nil {
		in, out := &in.Cycle, &out.Cycle
		*out = new(float64)
		**out = **in
	}
	if in.DownThreshold != nil {
		in, out := &in.DownThreshold, &out.DownThreshold
		*out = new(float64)
		**out = **in
	}
	if in.HTTPMethod != nil {
		in, out := &in.HTTPMethod, &out.HTTPMethod
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.URLPath != nil {
		in, out := &in.URLPath, &out.URLPath
		*out = new(string)
		**out = **in
	}
	if in.UpThreshold != nil {
		in, out := &in.UpThreshold, &out.UpThreshold
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckObservation.
func (in *HealthCheckObservation) DeepCopy() *HealthCheckObservation {
	if in == nil {
		return nil
	}
	out := new(HealthCheckObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckParameters) DeepCopyInto(out *HealthCheckParameters) {
	*out = *in
	if in.Cycle != nil {
		in, out := &in.Cycle, &out.Cycle
		*out = new(float64)
		**out = **in
	}
	if in.DownThreshold != nil {
		in, out := &in.DownThreshold, &out.DownThreshold
		*out = new(float64)
		**out = **in
	}
	if in.HTTPMethod != nil {
		in, out := &in.HTTPMethod, &out.HTTPMethod
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.URLPath != nil {
		in, out := &in.URLPath, &out.URLPath
		*out = new(string)
		**out = **in
	}
	if in.UpThreshold != nil {
		in, out := &in.UpThreshold, &out.UpThreshold
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckParameters.
func (in *HealthCheckParameters) DeepCopy() *HealthCheckParameters {
	if in == nil {
		return nil
	}
	out := new(HealthCheckParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Lb) DeepCopyInto(out *Lb) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Lb.
func (in *Lb) DeepCopy() *Lb {
	if in == nil {
		return nil
	}
	out := new(Lb)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Lb) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbInitParameters) DeepCopyInto(out *LbInitParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.IdleTimeout != nil {
		in, out := &in.IdleTimeout, &out.IdleTimeout
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NetworkType != nil {
		in, out := &in.NetworkType, &out.NetworkType
		*out = new(string)
		**out = **in
	}
	if in.SubnetNoList != nil {
		in, out := &in.SubnetNoList, &out.SubnetNoList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SubnetNoRefs != nil {
		in, out := &in.SubnetNoRefs, &out.SubnetNoRefs
		*out = make([]v1.NamespacedReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SubnetNoSelector != nil {
		in, out := &in.SubnetNoSelector, &out.SubnetNoSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ThroughputType != nil {
		in, out := &in.ThroughputType, &out.ThroughputType
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbInitParameters.
func (in *LbInitParameters) DeepCopy() *LbInitParameters {
	if in == nil {
		return nil
	}
	out := new(LbInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbList) DeepCopyInto(out *LbList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Lb, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbList.
func (in *LbList) DeepCopy() *LbList {
	if in == nil {
		return nil
	}
	out := new(LbList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LbList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListener) DeepCopyInto(out *LbListener) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListener.
func (in *LbListener) DeepCopy() *LbListener {
	if in == nil {
		return nil
	}
	out := new(LbListener)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LbListener) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListenerInitParameters) DeepCopyInto(out *LbListenerInitParameters) {
	*out = *in
	if in.LoadBalancerNo != nil {
		in, out := &in.LoadBalancerNo, &out.LoadBalancerNo
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerNoRef != nil {
		in, out := &in.LoadBalancerNoRef, &out.LoadBalancerNoRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.LoadBalancerNoSelector != nil {
		in, out := &in.LoadBalancerNoSelector, &out.LoadBalancerNoSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.SSLCertificateNo != nil {
		in, out := &in.SSLCertificateNo, &out.SSLCertificateNo
		*out = new(string)
		**out = **in
	}
	if in.TLSMinVersionType != nil {
		in, out := &in.TLSMinVersionType, &out.TLSMinVersionType
		*out = new(string)
		**out = **in
	}
	if in.TargetGroupNo != nil {
		in, out := &in.TargetGroupNo, &out.TargetGroupNo
		*out = new(string)
		**out = **in
	}
	if in.TargetGroupNoRef != nil {
		in, out := &in.TargetGroupNoRef, &out.TargetGroupNoRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetGroupNoSelector != nil {
		in, out := &in.TargetGroupNoSelector, &out.TargetGroupNoSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.UseHttp2 != nil {
		in, out := &in.UseHttp2, &out.UseHttp2
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListenerInitParameters.
func (in *LbListenerInitParameters) DeepCopy() *LbListenerInitParameters {
	if in == nil {
		return nil
	}
	out := new(LbListenerInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListenerList) DeepCopyInto(out *LbListenerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LbListener, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListenerList.
func (in *LbListenerList) DeepCopy() *LbListenerList {
	if in == nil {
		return nil
	}
	out := new(LbListenerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LbListenerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListenerObservation) DeepCopyInto(out *LbListenerObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ListenerNo != nil {
		in, out := &in.ListenerNo, &out.ListenerNo
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerNo != nil {
		in, out := &in.LoadBalancerNo, &out.LoadBalancerNo
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.RuleNoList != nil {
		in, out := &in.RuleNoList, &out.RuleNoList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SSLCertificateNo != nil {
		in, out := &in.SSLCertificateNo, &out.SSLCertificateNo
		*out = new(string)
		**out = **in
	}
	if in.TLSMinVersionType != nil {
		in, out := &in.TLSMinVersionType, &out.TLSMinVersionType
		*out = new(string)
		**out = **in
	}
	if in.TargetGroupNo != nil {
		in, out := &in.TargetGroupNo, &out.TargetGroupNo
		*out = new(string)
		**out = **in
	}
	if in.UseHttp2 != nil {
		in, out := &in.UseHttp2, &out.UseHttp2
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListenerObservation.
func (in *LbListenerObservation) DeepCopy() *LbListenerObservation {
	if in == nil {
		return nil
	}
	out := new(LbListenerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListenerParameters) DeepCopyInto(out *LbListenerParameters) {
	*out = *in
	if in.LoadBalancerNo != nil {
		in, out := &in.LoadBalancerNo, &out.LoadBalancerNo
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerNoRef != nil {
		in, out := &in.LoadBalancerNoRef, &out.LoadBalancerNoRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.LoadBalancerNoSelector != nil {
		in, out := &in.LoadBalancerNoSelector, &out.LoadBalancerNoSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.SSLCertificateNo != nil {
		in, out := &in.SSLCertificateNo, &out.SSLCertificateNo
		*out = new(string)
		**out = **in
	}
	if in.TLSMinVersionType != nil {
		in, out := &in.TLSMinVersionType, &out.TLSMinVersionType
		*out = new(string)
		**out = **in
	}
	if in.TargetGroupNo != nil {
		in, out := &in.TargetGroupNo, &out.TargetGroupNo
		*out = new(string)
		**out = **in
	}
	if in.TargetGroupNoRef != nil {
		in, out := &in.TargetGroupNoRef, &out.TargetGroupNoRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetGroupNoSelector != nil {
		in, out := &in.TargetGroupNoSelector, &out.TargetGroupNoSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.UseHttp2 != nil {
		in, out := &in.UseHttp2, &out.UseHttp2
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListenerParameters.
func (in *LbListenerParameters) DeepCopy() *LbListenerParameters {
	if in == nil {
		return nil
	}
	out := new(LbListenerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListenerSpec) DeepCopyInto(out *LbListenerSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListenerSpec.
func (in *LbListenerSpec) DeepCopy() *LbListenerSpec {
	if in == nil {
		return nil
	}
	out := new(LbListenerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListenerStatus) DeepCopyInto(out *LbListenerStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListenerStatus.
func (in *LbListenerStatus) DeepCopy() *LbListenerStatus {
	if in == nil {
		return nil
	}
	out := new(LbListenerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbObservation) DeepCopyInto(out *LbObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Domain != nil {
		in, out := &in.Domain, &out.Domain
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IPList != nil {
		in, out := &in.IPList, &out.IPList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IdleTimeout != nil {
		in, out := &in.IdleTimeout, &out.IdleTimeout
		*out = new(float64)
		**out = **in
	}
	if in.ListenerNoList != nil {
		in, out := &in.ListenerNoList, &out.ListenerNoList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.LoadBalancerNo != nil {
		in, out := &in.LoadBalancerNo, &out.LoadBalancerNo
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NetworkType != nil {
		in, out := &in.NetworkType, &out.NetworkType
		*out = new(string)
		**out = **in
	}
	if in.SubnetNoList != nil {
		in, out := &in.SubnetNoList, &out.SubnetNoList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ThroughputType != nil {
		in, out := &in.ThroughputType, &out.ThroughputType
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.VPCNo != nil {
		in, out := &in.VPCNo, &out.VPCNo
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbObservation.
func (in *LbObservation) DeepCopy() *LbObservation {
	if in == nil {
		return nil
	}
	out := new(LbObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbParameters) DeepCopyInto(out *LbParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.IdleTimeout != nil {
		in, out := &in.IdleTimeout, &out.IdleTimeout
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NetworkType != nil {
		in, out := &in.NetworkType, &out.NetworkType
		*out = new(string)
		**out = **in
	}
	if in.SubnetNoList != nil {
		in, out := &in.SubnetNoList, &out.SubnetNoList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SubnetNoRefs != nil {
		in, out := &in.SubnetNoRefs, &out.SubnetNoRefs
		*out = make([]v1.NamespacedReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SubnetNoSelector != nil {
		in, out := &in.SubnetNoSelector, &out.SubnetNoSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ThroughputType != nil {
		in, out := &in.ThroughputType, &out.ThroughputType
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbParameters.
func (in *LbParameters) DeepCopy() *LbParameters {
	if in == nil {
		return nil
	}
	out := new(LbParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbSpec) DeepCopyInto(out *LbSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbSpec.
func (in *LbSpec) DeepCopy() *LbSpec {
	if in == nil {
		return nil
	}
	out := new(LbSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbStatus) DeepCopyInto(out *LbStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbStatus.
func (in *LbStatus) DeepCopy() *LbStatus {
	if in == nil {
		return nil
	}
	out := new(LbStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbTargetGroup) DeepCopyInto(out *LbTargetGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbTargetGroup.
func (in *LbTargetGroup) DeepCopy() *LbTargetGroup {
	if in == nil {
		return nil
	}
	out := new(LbTargetGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LbTargetGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbTargetGroupAttachment) DeepCopyInto(out *LbTargetGroupAttachment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbTargetGroupAttachment.
func (in *LbTargetGroupAttachment) DeepCopy() *LbTargetGroupAttachment {
	if in == nil {
		return nil
	}
	out := new(LbTargetGroupAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LbTargetGroupAttachment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbTargetGroupAttachmentInitParameters) DeepCopyInto(out *LbTargetGroupAttachmentInitParameters) {
	*out = *in
	if in.TargetGroupNo != nil {
		in, out := &in.TargetGroupNo, &out.TargetGroupNo
		*out = new(string)
		**out = **in
	}
	if in.TargetGroupNoRef != nil {
		in, out := &in.TargetGroupNoRef, &out.TargetGroupNoRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetGroupNoSelector != nil {
		in, out := &in.TargetGroupNoSelector, &out.TargetGroupNoSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetNoList != nil {
		in, out := &in.TargetNoList, &out.TargetNoList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TargetNoRefs != nil {
		in, out := &in.TargetNoRefs, &out.TargetNoRefs
		*out = make([]v1.NamespacedReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TargetNoSelector != nil {
		in, out := &in.TargetNoSelector, &out.TargetNoSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbTargetGroupAttachmentInitParameters.
func (in *LbTargetGroupAttachmentInitParameters) DeepCopy() *LbTargetGroupAttachmentInitParameters {
	if in == nil {
		return nil
	}
	out := new(LbTargetGroupAttachmentInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbTargetGroupAttachmentList) DeepCopyInto(out *LbTargetGroupAttachmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LbTargetGroupAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbTargetGroupAttachmentList.
func (in *LbTargetGroupAttachmentList) DeepCopy() *LbTargetGroupAttachmentList {
	if in == nil {
		return nil
	}
	out := new(LbTargetGroupAttachmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LbTargetGroupAttachmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbTargetGroupAttachmentObservation) DeepCopyInto(out *LbTargetGroupAttachmentObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.TargetGroupNo != nil {
		in, out := &in.TargetGroupNo, &out.TargetGroupNo
		*out = new(string)
		**out = **in
	}
	if in.TargetNoList != nil {
		in, out := &in.TargetNoList, &out.TargetNoList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbTargetGroupAttachmentObservation.
func (in *LbTargetGroupAttachmentObservation) DeepCopy() *LbTargetGroupAttachmentObservation {
	if in == nil {
		return nil
	}
	out := new(LbTargetGroupAttachmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbTargetGroupAttachmentParameters) DeepCopyInto(out *LbTargetGroupAttachmentParameters) {
	*out = *in
	if in.TargetGroupNo != nil {
		in, out := &in.TargetGroupNo, &out.TargetGroupNo
		*out = new(string)
		**out = **in
	}
	if in.TargetGroupNoRef != nil {
		in, out := &in.TargetGroupNoRef, &out.TargetGroupNoRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetGroupNoSelector != nil {
		in, out := &in.TargetGroupNoSelector, &out.TargetGroupNoSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetNoList != nil {
		in, out := &in.TargetNoList, &out.TargetNoList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TargetNoRefs != nil {
		in, out := &in.TargetNoRefs, &out.TargetNoRefs
		*out = make([]v1.NamespacedReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TargetNoSelector != nil {
		in, out := &in.TargetNoSelector, &out.TargetNoSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbTargetGroupAttachmentParameters.
func (in *LbTargetGroupAttachmentParameters) DeepCopy() *LbTargetGroupAttachmentParameters {
	if in == nil {
		return nil
	}
	out := new(LbTargetGroupAttachmentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbTargetGroupAttachmentSpec) DeepCopyInto(out *LbTargetGroupAttachmentSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbTargetGroupAttachmentSpec.
func (in *LbTargetGroupAttachmentSpec) DeepCopy() *LbTargetGroupAttachmentSpec {
	if in == nil {
		return nil
	}
	out := new(LbTargetGroupAttachmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbTargetGroupAttachmentStatus) DeepCopyInto(out *LbTargetGroupAttachmentStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbTargetGroupAttachmentStatus.
func (in *LbTargetGroupAttachmentStatus) DeepCopy() *LbTargetGroupAttachmentStatus {
	if in == nil {
		return nil
	}
	out := new(LbTargetGroupAttachmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbTargetGroupInitParameters) DeepCopyInto(out *LbTargetGroupInitParameters) {
	*out = *in
	if in.AlgorithmType != nil {
		in, out := &in.AlgorithmType, &out.AlgorithmType
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = make([]HealthCheckInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.TargetType != nil {
		in, out := &in.TargetType, &out.TargetType
		*out = new(string)
		**out = **in
	}
	if in.UseProxyProtocol != nil {
		in, out := &in.UseProxyProtocol, &out.UseProxyProtocol
		*out = new(bool)
		**out = **in
	}
	if in.UseStickySession != nil {
		in, out := &in.UseStickySession, &out.UseStickySession
		*out = new(bool)
		**out = **in
	}
	if in.VPCNo != nil {
		in, out := &in.VPCNo, &out.VPCNo
		*out = new(string)
		**out = **in
	}
	if in.VPCNoRef != nil {
		in, out := &in.VPCNoRef, &out.VPCNoRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.VPCNoSelector != nil {
		in, out := &in.VPCNoSelector, &out.VPCNoSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbTargetGroupInitParameters.
func (in *LbTargetGroupInitParameters) DeepCopy() *LbTargetGroupInitParameters {
	if in == nil {
		return nil
	}
	out := new(LbTargetGroupInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbTargetGroupList) DeepCopyInto(out *LbTargetGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LbTargetGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbTargetGroupList.
func (in *LbTargetGroupList) DeepCopy() *LbTargetGroupList {
	if in == nil {
		return nil
	}
	out := new(LbTargetGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LbTargetGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbTargetGroupObservation) DeepCopyInto(out *LbTargetGroupObservation) {
	*out = *in
	if in.AlgorithmType != nil {
		in, out := &in.AlgorithmType, &out.AlgorithmType
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = make([]HealthCheckObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerInstanceNo != nil {
		in, out := &in.LoadBalancerInstanceNo, &out.LoadBalancerInstanceNo
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.TargetGroupNo != nil {
		in, out := &in.TargetGroupNo, &out.TargetGroupNo
		*out = new(string)
		**out = **in
	}
	if in.TargetNoList != nil {
		in, out := &in.TargetNoList, &out.TargetNoList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TargetType != nil {
		in, out := &in.TargetType, &out.TargetType
		*out = new(string)
		**out = **in
	}
	if in.UseProxyProtocol != nil {
		in, out := &in.UseProxyProtocol, &out.UseProxyProtocol
		*out = new(bool)
		**out = **in
	}
	if in.UseStickySession != nil {
		in, out := &in.UseStickySession, &out.UseStickySession
		*out = new(bool)
		**out = **in
	}
	if in.VPCNo != nil {
		in, out := &in.VPCNo, &out.VPCNo
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbTargetGroupObservation.
func (in *LbTargetGroupObservation) DeepCopy() *LbTargetGroupObservation {
	if in == nil {
		return nil
	}
	out := new(LbTargetGroupObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbTargetGroupParameters) DeepCopyInto(out *LbTargetGroupParameters) {
	*out = *in
	if in.AlgorithmType != nil {
		in, out := &in.AlgorithmType, &out.AlgorithmType
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = make([]HealthCheckParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.TargetType != nil {
		in, out := &in.TargetType, &out.TargetType
		*out = new(string)
		**out = **in
	}
	if in.UseProxyProtocol != nil {
		in, out := &in.UseProxyProtocol, &out.UseProxyProtocol
		*out = new(bool)
		**out = **in
	}
	if in.UseStickySession != nil {
		in, out := &in.UseStickySession, &out.UseStickySession
		*out = new(bool)
		**out = **in
	}
	if in.VPCNo != nil {
		in, out := &in.VPCNo, &out.VPCNo
		*out = new(string)
		**out = **in
	}
	if in.VPCNoRef != nil {
		in, out := &in.VPCNoRef, &out.VPCNoRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.VPCNoSelector != nil {
		in, out := &in.VPCNoSelector, &out.VPCNoSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbTargetGroupParameters.
func (in *LbTargetGroupParameters) DeepCopy() *LbTargetGroupParameters {
	if in == nil {
		return nil
	}
	out := new(LbTargetGroupParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbTargetGroupSpec) DeepCopyInto(out *LbTargetGroupSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbTargetGroupSpec.
func (in *LbTargetGroupSpec) DeepCopy() *LbTargetGroupSpec {
	if in == nil {
		return nil
	}
	out := new(LbTargetGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbTargetGroupStatus) DeepCopyInto(out *LbTargetGroupStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbTargetGroupStatus.
func (in *LbTargetGroupStatus) DeepCopy() *LbTargetGroupStatus {
	if in == nil {
		return nil
	}
	out := new(LbTargetGroupStatus)
	in.DeepCopyInto(out)
	return out
}
